-- ============================================================================
-- SEED TASKS FOR EMPTY PROJECTS
-- Populates the 7 projects that have 0 tasks
-- Run this in Supabase SQL Editor
-- ============================================================================

-- Temporarily disable RLS
ALTER TABLE tasks DISABLE ROW LEVEL SECURITY;

-- ============================================================================
-- 1. INSTALLER GTM & VALUE PROPOSITION TASKS
-- ============================================================================

INSERT INTO tasks (project_id, title, description, phase, status, priority, difficulty, owner_team_id, estimated_hours, ai_potential, ai_assist_description, tools_needed, knowledge_areas, acceptance_criteria, success_metrics, risks, is_foundational, is_critical_path, order_index)
VALUES
-- Discovery Phase
((SELECT id FROM projects WHERE slug = 'installer-gtm-value-prop'),
 'Installer Persona Research',
 'Conduct interviews with 10-15 current installers to understand their needs, pain points, and decision criteria. Document installer archetypes and buying journey.',
 'discovery', 'not_started', 'high', 'medium',
 (SELECT id FROM teams WHERE slug = 'sales'),
 '16-24h', 'medium',
 'Can help analyze interview transcripts and identify patterns',
 ARRAY['Interview tools', 'Notion', 'Recording software'],
 ARRAY['Customer Research', 'Market Analysis'],
 ARRAY['10+ installer interviews conducted', 'Persona documents created', 'Buying journey mapped', 'Key pain points identified'],
 ARRAY['Complete persona documentation', 'Validated by sales team'],
 ARRAY['Installer availability', 'Bias in sample'],
 true, true, 0),

((SELECT id FROM projects WHERE slug = 'installer-gtm-value-prop'),
 'Competitive Landscape Analysis',
 'Analyze competing installer platforms and their value propositions. Document feature comparisons, pricing strategies, and market positioning.',
 'discovery', 'not_started', 'high', 'medium',
 (SELECT id FROM teams WHERE slug = 'marketing'),
 '12-16h', 'high',
 'Can research competitors and generate comparison matrices',
 ARRAY['Web research', 'Spreadsheets', 'Notion'],
 ARRAY['Market Analysis', 'Competitive Intelligence'],
 ARRAY['5+ competitors analyzed', 'Feature comparison matrix', 'Pricing analysis complete', 'Differentiators identified'],
 ARRAY['Comprehensive competitive database'],
 ARRAY['Incomplete public information', 'Rapidly changing landscape'],
 true, false, 1),

-- Planning Phase
((SELECT id FROM projects WHERE slug = 'installer-gtm-value-prop'),
 'Value Proposition Framework Development',
 'Develop clear value proposition framework articulating why installers should join Abeto. Include ROI calculator, success stories framework, and key messaging.',
 'planning', 'not_started', 'critical', 'hard',
 (SELECT id FROM teams WHERE slug = 'marketing'),
 '20-28h', 'medium',
 'Can help draft messaging and calculate ROI scenarios',
 ARRAY['Copywriting tools', 'Spreadsheets', 'Design tools'],
 ARRAY['Marketing Strategy', 'Value Communication'],
 ARRAY['Core value proposition statement', 'Supporting proof points', 'ROI calculator model', 'Message testing plan'],
 ARRAY['Value prop approved by leadership'],
 ARRAY['Internal alignment', 'Unclear differentiation'],
 true, true, 2),

((SELECT id FROM projects WHERE slug = 'installer-gtm-value-prop'),
 'Pricing Strategy Definition',
 'Define installer pricing tiers, commission structures, and incentive programs. Model unit economics and margin analysis.',
 'planning', 'not_started', 'critical', 'hard',
 (SELECT id FROM teams WHERE slug = 'finance'),
 '16-24h', 'medium',
 'Can model financial scenarios and create pricing simulations',
 ARRAY['Spreadsheets', 'Financial modeling tools'],
 ARRAY['Financial Analysis', 'Pricing Strategy'],
 ARRAY['Pricing tiers defined', 'Commission structure documented', 'Unit economics validated', 'Competitive pricing analysis'],
 ARRAY['Profitable pricing model approved'],
 ARRAY['Market rejection', 'Margin pressure'],
 true, true, 3),

-- Development Phase
((SELECT id FROM projects WHERE slug = 'installer-gtm-value-prop'),
 'Sales Deck & Materials Creation',
 'Create comprehensive sales deck, one-pagers, and leave-behind materials for installer acquisition. Include case studies and testimonials.',
 'development', 'not_started', 'high', 'medium',
 (SELECT id FROM teams WHERE slug = 'marketing'),
 '24-32h', 'high',
 'Can draft content and suggest design improvements',
 ARRAY['Figma', 'Google Slides', 'Canva'],
 ARRAY['Content Creation', 'Sales Enablement'],
 ARRAY['Sales deck completed', 'One-pagers for each segment', 'Case study templates', 'Leave-behind materials'],
 ARRAY['Materials approved by sales'],
 ARRAY['Design delays', 'Content approval'],
 false, false, 4),

((SELECT id FROM projects WHERE slug = 'installer-gtm-value-prop'),
 'Installer Onboarding Journey Design',
 'Design the complete installer onboarding experience from signup to first installation. Include training requirements, certification process, and support touchpoints.',
 'development', 'not_started', 'high', 'hard',
 (SELECT id FROM teams WHERE slug = 'operations'),
 '20-28h', 'medium',
 'Can map journey and identify automation opportunities',
 ARRAY['Journey mapping tools', 'Notion', 'Process design'],
 ARRAY['Process Design', 'Customer Experience'],
 ARRAY['Onboarding journey mapped', 'Training curriculum defined', 'Certification requirements set', 'Support touchpoints identified'],
 ARRAY['Onboarding time under 48 hours'],
 ARRAY['Complexity', 'Drop-off rates'],
 true, true, 5),

-- Launch Phase
((SELECT id FROM projects WHERE slug = 'installer-gtm-value-prop'),
 'GTM Launch Campaign',
 'Execute go-to-market launch campaign for installer acquisition. Include digital marketing, events, partnerships, and referral programs.',
 'launch', 'not_started', 'critical', 'hard',
 (SELECT id FROM teams WHERE slug = 'marketing'),
 '40-60h', 'medium',
 'Can help with content creation and campaign optimization',
 ARRAY['Marketing automation', 'Analytics', 'Ad platforms'],
 ARRAY['Marketing Execution', 'Lead Generation'],
 ARRAY['Campaign live across channels', 'Lead tracking operational', 'Referral program active', 'Event calendar set'],
 ARRAY['50+ qualified installer leads per month'],
 ARRAY['Budget constraints', 'Market timing'],
 false, true, 6),

((SELECT id FROM projects WHERE slug = 'installer-gtm-value-prop'),
 'Sales Enablement & Training',
 'Train sales team on value proposition, objection handling, and demo process. Create sales playbook and competition battle cards.',
 'launch', 'not_started', 'high', 'medium',
 (SELECT id FROM teams WHERE slug = 'sales'),
 '16-24h', 'medium',
 'Can generate training materials and role-play scenarios',
 ARRAY['Training platform', 'Sales tools', 'Documentation'],
 ARRAY['Sales Training', 'Enablement'],
 ARRAY['Sales playbook complete', 'Team trained', 'Battle cards created', 'Demo scripts ready'],
 ARRAY['100% sales team certified'],
 ARRAY['Training adoption', 'Time constraints'],
 false, false, 7);

-- ============================================================================
-- 2. AI CUSTOMER SUCCESS AGENT TASKS
-- ============================================================================

INSERT INTO tasks (project_id, title, description, phase, status, priority, difficulty, owner_team_id, estimated_hours, ai_potential, ai_assist_description, tools_needed, knowledge_areas, acceptance_criteria, success_metrics, risks, is_foundational, is_critical_path, order_index)
VALUES
((SELECT id FROM projects WHERE slug = 'ai-customer-success-agent'),
 'CS Agent Requirements & Use Cases',
 'Document all customer success scenarios the AI agent should handle. Include proactive outreach triggers, health scoring criteria, and escalation rules.',
 'discovery', 'not_started', 'critical', 'medium',
 (SELECT id FROM teams WHERE slug = 'operations'),
 '16-20h', 'medium',
 'Can help categorize use cases and suggest automation opportunities',
 ARRAY['Notion', 'CRM data', 'Support tickets'],
 ARRAY['Customer Success', 'Process Design'],
 ARRAY['All CS scenarios documented', 'Health scoring model defined', 'Escalation matrix created', 'Automation opportunities identified'],
 ARRAY['Comprehensive use case library'],
 ARRAY['Missing edge cases', 'Changing requirements'],
 true, true, 0),

((SELECT id FROM projects WHERE slug = 'ai-customer-success-agent'),
 'Churn Prediction Model Design',
 'Design machine learning model to predict customer churn risk. Identify key signals, data requirements, and intervention thresholds.',
 'planning', 'not_started', 'critical', 'hard',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '24-32h', 'high',
 'Can design model architecture and feature engineering',
 ARRAY['Python', 'ML frameworks', 'Data warehouse'],
 ARRAY['Machine Learning', 'Data Science'],
 ARRAY['Model architecture defined', 'Features identified', 'Training data requirements', 'Accuracy targets set'],
 ARRAY['Model design approved by data team'],
 ARRAY['Data quality issues', 'Model complexity'],
 true, true, 1),

((SELECT id FROM projects WHERE slug = 'ai-customer-success-agent'),
 'Proactive Intervention Workflows',
 'Build automated workflows for proactive customer outreach based on health scores and behavior signals.',
 'development', 'not_started', 'high', 'hard',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '28-36h', 'high',
 'Can generate workflow logic and message templates',
 ARRAY['Workflow automation', 'Messaging APIs', 'CRM'],
 ARRAY['Automation', 'Customer Communication'],
 ARRAY['Workflows deployed', 'Trigger conditions working', 'Message personalization active', 'A/B testing enabled'],
 ARRAY['Workflows processing 100+ customers/day'],
 ARRAY['Over-communication', 'Timing issues'],
 false, true, 2),

((SELECT id FROM projects WHERE slug = 'ai-customer-success-agent'),
 'CS Agent Conversation Handling',
 'Implement AI-powered conversation handling for common customer inquiries. Include intent recognition, response generation, and handoff to humans.',
 'development', 'not_started', 'critical', 'hard',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '32-40h', 'high',
 'This IS the AI agent - will use LLM for conversations',
 ARRAY['LLM APIs', 'Chat platform', 'Knowledge base'],
 ARRAY['NLP', 'Conversational AI'],
 ARRAY['Intent recognition working', 'Response quality validated', 'Handoff logic implemented', 'Conversation history tracked'],
 ARRAY['80% query resolution without human'],
 ARRAY['Response quality', 'Edge cases'],
 true, true, 3),

((SELECT id FROM projects WHERE slug = 'ai-customer-success-agent'),
 'Installer Health Dashboard',
 'Build dashboard showing installer health scores, engagement metrics, and recommended actions for CS team.',
 'development', 'not_started', 'high', 'medium',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '20-28h', 'medium',
 'Can help design dashboard layout and metrics',
 ARRAY['React', 'Chart libraries', 'API'],
 ARRAY['Frontend', 'Data Visualization'],
 ARRAY['Dashboard deployed', 'Health scores visible', 'Action recommendations shown', 'Filtering and search working'],
 ARRAY['Dashboard used daily by CS team'],
 ARRAY['Performance', 'Data freshness'],
 false, false, 4),

((SELECT id FROM projects WHERE slug = 'ai-customer-success-agent'),
 'CS Agent Testing & Validation',
 'Comprehensive testing of AI agent including accuracy testing, edge case handling, and user acceptance testing with CS team.',
 'testing', 'not_started', 'critical', 'medium',
 (SELECT id FROM teams WHERE slug = 'operations'),
 '16-24h', 'medium',
 'Can generate test cases and analyze results',
 ARRAY['Testing tools', 'Staging environment'],
 ARRAY['QA', 'User Testing'],
 ARRAY['Test cases executed', 'Accuracy benchmarks met', 'CS team validated', 'Edge cases handled'],
 ARRAY['95% test pass rate'],
 ARRAY['Hidden issues', 'User adoption'],
 false, true, 5);

-- ============================================================================
-- 3. INSTALLER ENABLEMENT & TRAINING PLATFORM TASKS
-- ============================================================================

INSERT INTO tasks (project_id, title, description, phase, status, priority, difficulty, owner_team_id, estimated_hours, ai_potential, ai_assist_description, tools_needed, knowledge_areas, acceptance_criteria, success_metrics, risks, is_foundational, is_critical_path, order_index)
VALUES
((SELECT id FROM projects WHERE slug = 'installer-enablement-training'),
 'Training Needs Assessment',
 'Survey installers and analyze support tickets to identify knowledge gaps. Document required competencies and skill levels.',
 'discovery', 'not_started', 'high', 'medium',
 (SELECT id FROM teams WHERE slug = 'operations'),
 '12-16h', 'medium',
 'Can analyze support data and identify patterns',
 ARRAY['Survey tools', 'Support data', 'Notion'],
 ARRAY['Training Design', 'Customer Research'],
 ARRAY['Survey completed with 50+ responses', 'Knowledge gaps documented', 'Competency matrix created', 'Priority topics identified'],
 ARRAY['Complete training needs assessment'],
 ARRAY['Low survey response', 'Bias in responses'],
 true, true, 0),

((SELECT id FROM projects WHERE slug = 'installer-enablement-training'),
 'Curriculum Design & Structure',
 'Design training curriculum including modules, progression paths, and certification levels. Map content to installer journey stages.',
 'planning', 'not_started', 'critical', 'hard',
 (SELECT id FROM teams WHERE slug = 'operations'),
 '20-28h', 'medium',
 'Can suggest content structure and learning objectives',
 ARRAY['Notion', 'LMS research', 'Instructional design'],
 ARRAY['Instructional Design', 'Content Strategy'],
 ARRAY['Curriculum outline complete', 'Module descriptions written', 'Progression paths defined', 'Certification criteria set'],
 ARRAY['Curriculum approved by leadership'],
 ARRAY['Scope creep', 'Content gaps'],
 true, true, 1),

((SELECT id FROM projects WHERE slug = 'installer-enablement-training'),
 'LMS Platform Selection & Setup',
 'Evaluate and select learning management system. Configure platform, set up user management, and integrate with installer database.',
 'planning', 'not_started', 'high', 'medium',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '16-24h', 'low',
 'Platform selection requires human evaluation',
 ARRAY['LMS platforms', 'Integration tools'],
 ARRAY['Platform Evaluation', 'Integration'],
 ARRAY['3+ LMS evaluated', 'Platform selected', 'Basic setup complete', 'User management configured'],
 ARRAY['LMS operational'],
 ARRAY['Integration complexity', 'Cost overruns'],
 true, false, 2),

((SELECT id FROM projects WHERE slug = 'installer-enablement-training'),
 'Video Training Content Production',
 'Produce video training content for core modules including platform tutorials, best practices, and troubleshooting guides.',
 'development', 'not_started', 'high', 'hard',
 (SELECT id FROM teams WHERE slug = 'marketing'),
 '40-60h', 'medium',
 'Can help script videos and suggest visuals',
 ARRAY['Video production', 'Screen recording', 'Editing software'],
 ARRAY['Video Production', 'Content Creation'],
 ARRAY['10+ training videos produced', 'Videos under 10 min each', 'Quizzes integrated', 'Captions added'],
 ARRAY['80% video completion rate'],
 ARRAY['Production delays', 'Quality issues'],
 false, true, 3),

((SELECT id FROM projects WHERE slug = 'installer-enablement-training'),
 'Interactive Practice Simulations',
 'Build interactive simulations for installers to practice key workflows in a safe environment.',
 'development', 'not_started', 'medium', 'hard',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '24-32h', 'high',
 'Can help design simulation scenarios',
 ARRAY['Simulation tools', 'Frontend', 'Staging data'],
 ARRAY['Interactive Design', 'Simulation'],
 ARRAY['3+ simulations built', 'Realistic scenarios', 'Feedback provided', 'Progress tracked'],
 ARRAY['Simulations used by 50% of installers'],
 ARRAY['Complexity', 'Maintenance burden'],
 false, false, 4),

((SELECT id FROM projects WHERE slug = 'installer-enablement-training'),
 'Certification Program Launch',
 'Launch installer certification program with exams, badges, and recognition. Track certification rates and correlate with performance.',
 'launch', 'not_started', 'high', 'medium',
 (SELECT id FROM teams WHERE slug = 'operations'),
 '16-24h', 'medium',
 'Can help design exam questions and track metrics',
 ARRAY['LMS', 'Badge system', 'Analytics'],
 ARRAY['Program Management', 'Assessment'],
 ARRAY['Certification exams live', 'Badges awarded', 'Public recognition system', 'Performance correlation tracked'],
 ARRAY['30% installers certified in 3 months'],
 ARRAY['Low adoption', 'Exam gaming'],
 false, true, 5);

-- ============================================================================
-- 4. INCIDENT & BUG MANAGEMENT SYSTEM TASKS
-- ============================================================================

INSERT INTO tasks (project_id, title, description, phase, status, priority, difficulty, owner_team_id, estimated_hours, ai_potential, ai_assist_description, tools_needed, knowledge_areas, acceptance_criteria, success_metrics, risks, is_foundational, is_critical_path, order_index)
VALUES
((SELECT id FROM projects WHERE slug = 'incident-bug-management'),
 'Incident Classification Framework',
 'Define incident severity levels, categories, and response SLAs. Create decision tree for triage and escalation.',
 'discovery', 'not_started', 'critical', 'medium',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '12-16h', 'medium',
 'Can help define categories based on historical data',
 ARRAY['Notion', 'Historical incident data'],
 ARRAY['Incident Management', 'Process Design'],
 ARRAY['Severity levels defined', 'Categories documented', 'SLAs established', 'Escalation paths clear'],
 ARRAY['Framework approved by all teams'],
 ARRAY['Edge cases', 'Team disagreement'],
 true, true, 0),

((SELECT id FROM projects WHERE slug = 'incident-bug-management'),
 'Bug Tracking System Setup',
 'Configure bug tracking system with custom fields, workflows, and integrations. Set up reporting and dashboards.',
 'planning', 'not_started', 'high', 'medium',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '16-24h', 'medium',
 'Can help design workflows and custom fields',
 ARRAY['Bug tracking tool', 'Integrations'],
 ARRAY['Tool Configuration', 'Workflow Design'],
 ARRAY['System configured', 'Workflows set up', 'Integrations working', 'Dashboards created'],
 ARRAY['System adopted by all teams'],
 ARRAY['Adoption resistance', 'Configuration complexity'],
 true, true, 1),

((SELECT id FROM projects WHERE slug = 'incident-bug-management'),
 'AI Bug Triage Automation',
 'Implement AI-powered bug triage to automatically categorize, prioritize, and assign incoming bugs based on content and historical patterns.',
 'development', 'not_started', 'high', 'hard',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '24-32h', 'high',
 'This IS AI automation - will use ML for classification',
 ARRAY['ML models', 'Bug tracker API', 'Training data'],
 ARRAY['Machine Learning', 'NLP'],
 ARRAY['Auto-categorization working', 'Priority prediction accurate', 'Assignment logic implemented', 'Override capability exists'],
 ARRAY['80% triage accuracy'],
 ARRAY['Model accuracy', 'Edge cases'],
 false, true, 2),

((SELECT id FROM projects WHERE slug = 'incident-bug-management'),
 'Customer Notification System',
 'Build automated customer notification system for incident updates. Include status page, email notifications, and in-app alerts.',
 'development', 'not_started', 'high', 'medium',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '20-28h', 'high',
 'Can generate notification templates and logic',
 ARRAY['Notification service', 'Status page tool', 'Email service'],
 ARRAY['Communication', 'Integration'],
 ARRAY['Status page live', 'Email notifications working', 'In-app alerts functional', 'Subscriber management active'],
 ARRAY['Customers notified within 5 min of incidents'],
 ARRAY['Notification fatigue', 'Delivery issues'],
 false, false, 3),

((SELECT id FROM projects WHERE slug = 'incident-bug-management'),
 'Post-Mortem Process & Templates',
 'Create post-mortem process and templates for significant incidents. Include root cause analysis, action items, and learning documentation.',
 'development', 'not_started', 'medium', 'easy',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '8-12h', 'medium',
 'Can help generate templates and analysis frameworks',
 ARRAY['Notion', 'Templates'],
 ARRAY['Process Design', 'Documentation'],
 ARRAY['Post-mortem template created', 'Process documented', 'Meeting cadence set', 'Action tracking in place'],
 ARRAY['Post-mortems completed for all P0/P1'],
 ARRAY['Process fatigue', 'Blame culture'],
 false, false, 4),

((SELECT id FROM projects WHERE slug = 'incident-bug-management'),
 'Resolution Tracking Dashboard',
 'Build dashboard tracking bug resolution metrics, SLA compliance, and team performance. Include trend analysis and forecasting.',
 'development', 'not_started', 'medium', 'medium',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '16-24h', 'medium',
 'Can help design metrics and visualizations',
 ARRAY['Dashboard tools', 'Data warehouse', 'Chart libraries'],
 ARRAY['Data Visualization', 'Metrics'],
 ARRAY['Dashboard deployed', 'Key metrics visible', 'SLA tracking working', 'Trend analysis available'],
 ARRAY['Dashboard used in weekly reviews'],
 ARRAY['Data accuracy', 'Performance'],
 false, false, 5);

-- ============================================================================
-- 5. INTERNAL OPERATIONS AGENT SUITE TASKS
-- ============================================================================

INSERT INTO tasks (project_id, title, description, phase, status, priority, difficulty, owner_team_id, estimated_hours, ai_potential, ai_assist_description, tools_needed, knowledge_areas, acceptance_criteria, success_metrics, risks, is_foundational, is_critical_path, order_index)
VALUES
((SELECT id FROM projects WHERE slug = 'internal-ops-agent-suite'),
 'Internal Process Audit',
 'Audit all internal operations processes to identify repetitive tasks suitable for AI automation. Document time spent and automation potential.',
 'discovery', 'not_started', 'high', 'medium',
 (SELECT id FROM teams WHERE slug = 'operations'),
 '16-24h', 'medium',
 'Can help analyze processes and identify patterns',
 ARRAY['Process documentation', 'Time tracking', 'Interviews'],
 ARRAY['Process Analysis', 'Operations'],
 ARRAY['All processes documented', 'Time analysis complete', 'Automation candidates ranked', 'ROI estimated'],
 ARRAY['Comprehensive process inventory'],
 ARRAY['Incomplete documentation', 'Resistance to change'],
 true, true, 0),

((SELECT id FROM projects WHERE slug = 'internal-ops-agent-suite'),
 'Agent Architecture Design',
 'Design the architecture for internal AI agents including shared components, agent-specific modules, and orchestration layer.',
 'planning', 'not_started', 'critical', 'hard',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '20-28h', 'high',
 'Can help design agent architecture and patterns',
 ARRAY['Architecture tools', 'Documentation'],
 ARRAY['System Architecture', 'AI Design'],
 ARRAY['Architecture documented', 'Shared components identified', 'Agent interfaces defined', 'Orchestration approach set'],
 ARRAY['Architecture approved by tech lead'],
 ARRAY['Over-engineering', 'Integration complexity'],
 true, true, 1),

((SELECT id FROM projects WHERE slug = 'internal-ops-agent-suite'),
 'Data Entry Automation Agent',
 'Build AI agent to automate repetitive data entry tasks across systems. Include validation, error handling, and audit logging.',
 'development', 'not_started', 'high', 'hard',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '28-36h', 'high',
 'This IS the AI agent for data entry automation',
 ARRAY['RPA tools', 'API integrations', 'LLM'],
 ARRAY['Automation', 'Integration'],
 ARRAY['Agent operational', 'Data entry automated', 'Validation working', 'Error handling robust'],
 ARRAY['50% reduction in manual data entry'],
 ARRAY['Data quality', 'System changes'],
 false, true, 2),

((SELECT id FROM projects WHERE slug = 'internal-ops-agent-suite'),
 'Report Generation Agent',
 'Build AI agent to automatically generate routine reports by pulling data from multiple sources and formatting outputs.',
 'development', 'not_started', 'high', 'medium',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '24-32h', 'high',
 'This IS the AI agent for report generation',
 ARRAY['Data connectors', 'Report templates', 'LLM'],
 ARRAY['Data Processing', 'Reporting'],
 ARRAY['Agent generating reports', 'Multiple formats supported', 'Scheduling working', 'Distribution automated'],
 ARRAY['10+ hours/week saved on reporting'],
 ARRAY['Data accuracy', 'Format requirements'],
 false, false, 3),

((SELECT id FROM projects WHERE slug = 'internal-ops-agent-suite'),
 'Meeting Scheduling Agent',
 'Build AI agent to handle internal meeting scheduling, calendar management, and follow-up coordination.',
 'development', 'not_started', 'medium', 'medium',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '20-28h', 'high',
 'This IS the AI agent for scheduling',
 ARRAY['Calendar APIs', 'Email integration', 'LLM'],
 ARRAY['Calendar Management', 'Communication'],
 ARRAY['Agent scheduling meetings', 'Calendar conflicts resolved', 'Follow-ups automated', 'Preferences learned'],
 ARRAY['80% scheduling handled by agent'],
 ARRAY['Calendar complexity', 'User preferences'],
 false, false, 4),

((SELECT id FROM projects WHERE slug = 'internal-ops-agent-suite'),
 'Agent Monitoring & Analytics',
 'Build monitoring dashboard for all internal agents including performance metrics, error rates, and usage analytics.',
 'development', 'not_started', 'medium', 'medium',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '16-24h', 'medium',
 'Can help design metrics and alerts',
 ARRAY['Monitoring tools', 'Dashboard', 'Alerting'],
 ARRAY['Monitoring', 'Analytics'],
 ARRAY['Dashboard live', 'All agents monitored', 'Alerts configured', 'Usage tracked'],
 ARRAY['99%+ agent uptime'],
 ARRAY['Alert fatigue', 'Missing metrics'],
 false, false, 5);

-- ============================================================================
-- 6. AGENT COMMUNICATION PROTOCOL TASKS
-- ============================================================================

INSERT INTO tasks (project_id, title, description, phase, status, priority, difficulty, owner_team_id, estimated_hours, ai_potential, ai_assist_description, tools_needed, knowledge_areas, acceptance_criteria, success_metrics, risks, is_foundational, is_critical_path, order_index)
VALUES
((SELECT id FROM projects WHERE slug = 'agent-communication-protocol'),
 'Protocol Requirements Analysis',
 'Analyze communication requirements between all AI agents. Document message types, data formats, and interaction patterns.',
 'discovery', 'not_started', 'critical', 'hard',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '16-24h', 'medium',
 'Can help analyze patterns and suggest standards',
 ARRAY['Documentation', 'Agent specs', 'Message analysis'],
 ARRAY['Protocol Design', 'System Analysis'],
 ARRAY['All agent interactions mapped', 'Message types cataloged', 'Data formats documented', 'Patterns identified'],
 ARRAY['Complete interaction matrix'],
 ARRAY['Missing use cases', 'Evolving requirements'],
 true, true, 0),

((SELECT id FROM projects WHERE slug = 'agent-communication-protocol'),
 'Message Schema Design',
 'Design standardized message schemas for agent-to-agent communication. Include versioning, validation, and extensibility.',
 'planning', 'not_started', 'critical', 'hard',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '20-28h', 'high',
 'Can help design schemas and generate documentation',
 ARRAY['Schema tools', 'Documentation', 'Validation'],
 ARRAY['Schema Design', 'API Design'],
 ARRAY['Schema specification complete', 'Versioning strategy defined', 'Validation rules set', 'Extension points documented'],
 ARRAY['Schema approved by all agent teams'],
 ARRAY['Breaking changes', 'Over-complexity'],
 true, true, 1),

((SELECT id FROM projects WHERE slug = 'agent-communication-protocol'),
 'Message Queue Infrastructure',
 'Set up message queue infrastructure for asynchronous agent communication. Include routing, retry logic, and dead letter handling.',
 'development', 'not_started', 'critical', 'hard',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '24-32h', 'medium',
 'Can help configure queues and routing rules',
 ARRAY['Message queue', 'Infrastructure', 'Monitoring'],
 ARRAY['Infrastructure', 'Message Queues'],
 ARRAY['Queue infrastructure deployed', 'Routing working', 'Retry logic implemented', 'Dead letter handling active'],
 ARRAY['99.9% message delivery'],
 ARRAY['Infrastructure costs', 'Complexity'],
 true, true, 2),

((SELECT id FROM projects WHERE slug = 'agent-communication-protocol'),
 'Protocol SDK Development',
 'Build SDK/library for agents to easily implement communication protocol. Include documentation and examples.',
 'development', 'not_started', 'high', 'hard',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '28-36h', 'high',
 'Can help generate SDK code and documentation',
 ARRAY['SDK tools', 'Multiple languages', 'Testing'],
 ARRAY['SDK Development', 'Documentation'],
 ARRAY['SDK published', 'Documentation complete', 'Examples provided', 'Tests passing'],
 ARRAY['SDK adopted by all agents'],
 ARRAY['Adoption friction', 'Maintenance burden'],
 false, true, 3),

((SELECT id FROM projects WHERE slug = 'agent-communication-protocol'),
 'Protocol Security & Authentication',
 'Implement security layer for agent communication including authentication, encryption, and audit logging.',
 'development', 'not_started', 'critical', 'hard',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '20-28h', 'medium',
 'Can help design security patterns',
 ARRAY['Security tools', 'Encryption', 'Audit logging'],
 ARRAY['Security', 'Authentication'],
 ARRAY['Authentication implemented', 'Encryption in transit', 'Audit logging active', 'Security reviewed'],
 ARRAY['Zero unauthorized access'],
 ARRAY['Security vulnerabilities', 'Performance impact'],
 true, false, 4),

((SELECT id FROM projects WHERE slug = 'agent-communication-protocol'),
 'Protocol Testing & Validation',
 'Comprehensive testing of communication protocol including load testing, failure scenarios, and integration testing.',
 'testing', 'not_started', 'high', 'medium',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '16-24h', 'medium',
 'Can help generate test scenarios',
 ARRAY['Testing tools', 'Load testing', 'Chaos engineering'],
 ARRAY['Testing', 'QA'],
 ARRAY['Unit tests complete', 'Integration tests passing', 'Load testing done', 'Failure scenarios tested'],
 ARRAY['100% test coverage'],
 ARRAY['Hidden bugs', 'Edge cases'],
 false, true, 5);

-- ============================================================================
-- 7. CORTEX DATA ACQUISITION STRATEGY TASKS
-- ============================================================================

INSERT INTO tasks (project_id, title, description, phase, status, priority, difficulty, owner_team_id, estimated_hours, ai_potential, ai_assist_description, tools_needed, knowledge_areas, acceptance_criteria, success_metrics, risks, is_foundational, is_critical_path, order_index)
VALUES
((SELECT id FROM projects WHERE slug = 'cortex-data-acquisition'),
 'Data Source Inventory',
 'Create comprehensive inventory of all potential data sources for Cortex training. Evaluate quality, accessibility, and legal considerations.',
 'discovery', 'not_started', 'critical', 'medium',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '16-24h', 'medium',
 'Can help research data sources and evaluate quality',
 ARRAY['Research tools', 'Documentation', 'Legal review'],
 ARRAY['Data Research', 'Legal Compliance'],
 ARRAY['All data sources identified', 'Quality scores assigned', 'Access methods documented', 'Legal review complete'],
 ARRAY['100+ potential data sources evaluated'],
 ARRAY['Data access issues', 'Legal restrictions'],
 true, true, 0),

((SELECT id FROM projects WHERE slug = 'cortex-data-acquisition'),
 'Data Quality Framework',
 'Define data quality standards and validation rules for Cortex training data. Include quality metrics and remediation processes.',
 'planning', 'not_started', 'critical', 'hard',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '20-28h', 'high',
 'Can help define quality rules and validation logic',
 ARRAY['Data quality tools', 'Documentation', 'Validation'],
 ARRAY['Data Quality', 'Standards'],
 ARRAY['Quality standards defined', 'Validation rules created', 'Metrics established', 'Remediation process set'],
 ARRAY['Quality framework approved'],
 ARRAY['Evolving requirements', 'Enforcement challenges'],
 true, true, 1),

((SELECT id FROM projects WHERE slug = 'cortex-data-acquisition'),
 'Data Pipeline Architecture',
 'Design data pipeline architecture for collecting, processing, and storing training data. Include ETL processes and data lineage.',
 'planning', 'not_started', 'critical', 'hard',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '24-32h', 'high',
 'Can help design pipeline and generate configs',
 ARRAY['Data pipeline tools', 'Architecture', 'Storage'],
 ARRAY['Data Engineering', 'Architecture'],
 ARRAY['Pipeline architecture documented', 'ETL processes defined', 'Storage strategy set', 'Lineage tracking planned'],
 ARRAY['Architecture approved by data team'],
 ARRAY['Complexity', 'Scale challenges'],
 true, true, 2),

((SELECT id FROM projects WHERE slug = 'cortex-data-acquisition'),
 'Installer Interaction Data Collection',
 'Implement collection of installer interaction data including platform usage, support conversations, and performance metrics.',
 'development', 'not_started', 'high', 'medium',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '20-28h', 'medium',
 'Can help design collection points and schemas',
 ARRAY['Event tracking', 'Data pipeline', 'Storage'],
 ARRAY['Data Collection', 'Privacy'],
 ARRAY['Collection points implemented', 'Data flowing to pipeline', 'Privacy compliance verified', 'Quality checks active'],
 ARRAY['90% of interactions captured'],
 ARRAY['Privacy concerns', 'Data volume'],
 false, true, 3),

((SELECT id FROM projects WHERE slug = 'cortex-data-acquisition'),
 'External Data Integration',
 'Integrate external data sources including market data, weather, energy prices, and regulatory information.',
 'development', 'not_started', 'high', 'hard',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '28-36h', 'medium',
 'Can help design integrations and transformations',
 ARRAY['API integrations', 'Data transformation', 'Scheduling'],
 ARRAY['Integration', 'Data Processing'],
 ARRAY['External sources connected', 'Data transformations working', 'Refresh schedules set', 'Quality monitoring active'],
 ARRAY['5+ external sources integrated'],
 ARRAY['API changes', 'Data costs'],
 false, false, 4),

((SELECT id FROM projects WHERE slug = 'cortex-data-acquisition'),
 'Data Labeling & Annotation',
 'Set up data labeling process for supervised learning datasets. Include annotation tools, guidelines, and quality control.',
 'development', 'not_started', 'high', 'medium',
 (SELECT id FROM teams WHERE slug = 'operations'),
 '24-32h', 'medium',
 'Can assist with annotation guidelines and QC',
 ARRAY['Labeling tools', 'Guidelines', 'QC process'],
 ARRAY['Data Annotation', 'Quality Control'],
 ARRAY['Labeling tool configured', 'Guidelines documented', 'QC process established', 'Initial dataset labeled'],
 ARRAY['10,000+ labeled examples'],
 ARRAY['Labeling quality', 'Time investment'],
 false, true, 5);

-- Re-enable RLS
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;

-- Verify task counts
SELECT p.title, COUNT(t.id) as task_count
FROM projects p
LEFT JOIN tasks t ON t.project_id = p.id
WHERE p.slug IN (
  'installer-gtm-value-prop',
  'ai-customer-success-agent',
  'installer-enablement-training',
  'incident-bug-management',
  'internal-ops-agent-suite',
  'agent-communication-protocol',
  'cortex-data-acquisition'
)
GROUP BY p.title
ORDER BY p.title;
