-- ============================================================================
-- SEED TASKS: Detailed COO-level tasks for all projects
-- Run this in Supabase SQL Editor after seeding projects
-- ============================================================================

-- Temporarily disable RLS
ALTER TABLE tasks DISABLE ROW LEVEL SECURITY;

-- Clear existing tasks
DELETE FROM tasks;

-- ============================================================================
-- UNIFIED DATA LAYER TASKS
-- ============================================================================

INSERT INTO tasks (project_id, title, description, phase, status, priority, difficulty, owner_team_id, estimated_hours, ai_potential, ai_assist_description, tools_needed, knowledge_areas, acceptance_criteria, success_metrics, risks, is_foundational, is_critical_path, order_index)
VALUES
-- Discovery Phase
((SELECT id FROM projects WHERE slug = 'unified-data-layer'),
 'Data Audit & Gap Analysis',
 'Audit all existing data sources (Zoho, Woztell, Aircall, Holded). Document current data flows, identify gaps, inconsistencies, and missing fields. Create data dictionary.',
 'discovery', 'not_started', 'high', 'medium',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '16-24h', 'medium',
 'Can help analyze data schemas and generate documentation templates',
 ARRAY['Notion', 'Spreadsheets', 'Existing system access'],
 ARRAY['Data Analytics', 'Business Logic'],
 ARRAY['Complete inventory of all data sources', 'Data dictionary with field definitions', 'Gap analysis document with prioritized missing data', 'Data flow diagrams for current state'],
 ARRAY['100% of data sources documented', 'All critical gaps identified'],
 ARRAY['Access delays to production systems', 'Undocumented legacy data'],
 true, true, 0),

((SELECT id FROM projects WHERE slug = 'unified-data-layer'),
 'Stakeholder Requirements Workshop',
 'Conduct workshops with Sales, Ops, Finance, and Leadership to understand data needs. Document use cases, reporting requirements, and pain points.',
 'discovery', 'not_started', 'high', 'easy',
 (SELECT id FROM teams WHERE slug = 'operations'),
 '8-12h', 'low',
 'Can help structure workshop agenda and document outputs',
 ARRAY['Meeting tools', 'Notion', 'Whiteboard'],
 ARRAY['Stakeholder Management', 'Business Logic'],
 ARRAY['Workshop conducted with all key stakeholders', 'Requirements document approved by stakeholders', 'Priority ranking of data needs', 'Success criteria defined for each use case'],
 ARRAY[]::text[],
 ARRAY['Stakeholder availability', 'Conflicting requirements'],
 false, true, 1),

-- Planning Phase
((SELECT id FROM projects WHERE slug = 'unified-data-layer'),
 'API Architecture Design',
 'Design API architecture including endpoints, authentication, rate limiting, caching strategy. Define data models and relationships. Create technical specification document.',
 'planning', 'not_started', 'critical', 'hard',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '20-30h', 'high',
 'Can generate OpenAPI specs, data models, and architecture diagrams',
 ARRAY['Architecture tools', 'Documentation'],
 ARRAY['API Integration', 'Database/SQL', 'Security/Auth'],
 ARRAY['OpenAPI specification document', 'Database schema design', 'Authentication flow documented', 'Caching strategy defined', 'Rate limiting rules specified'],
 ARRAY[]::text[],
 ARRAY[]::text[],
 true, true, 2),

((SELECT id FROM projects WHERE slug = 'unified-data-layer'),
 'Third-Party API Access & Contracts',
 'Secure API access and documentation for all third-party systems. Negotiate contracts if needed. Document API limits, costs, and SLAs.',
 'planning', 'not_started', 'high', 'medium',
 (SELECT id FROM teams WHERE slug = 'operations'),
 '8-16h', 'low',
 'Vendor negotiation requires human judgment',
 ARRAY['Contract management', 'Vendor portals'],
 ARRAY['Vendor Management', 'Compliance/Legal'],
 ARRAY['Zoho API access confirmed with documented limits', 'Woztell API access and documentation obtained', 'Aircall API credentials and documentation', 'Holded API access for financial data', 'All API rate limits and costs documented'],
 ARRAY[]::text[],
 ARRAY['Vendor delays', 'Unexpected costs', 'API limitations'],
 false, false, 3),

-- Development Phase
((SELECT id FROM projects WHERE slug = 'unified-data-layer'),
 'Core API Infrastructure Setup',
 'Set up API server, database, authentication system, logging, and monitoring. Deploy to staging environment.',
 'development', 'not_started', 'critical', 'hard',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '24-32h', 'high',
 'Can generate boilerplate code, database migrations, and deployment configs',
 ARRAY['Node.js', 'PostgreSQL', 'Vercel/Railway', 'Auth0/JWT'],
 ARRAY['API Integration', 'Database/SQL', 'DevOps', 'Security/Auth'],
 ARRAY['API server running in staging', 'Database deployed and accessible', 'Authentication system working', 'Logging and monitoring active', 'CI/CD pipeline configured'],
 ARRAY[]::text[],
 ARRAY[]::text[],
 true, true, 4),

((SELECT id FROM projects WHERE slug = 'unified-data-layer'),
 'Deals & Opportunities Endpoints',
 'Build endpoints for Deals and Opportunities including CRUD operations, filtering, pagination, and Zoho sync.',
 'development', 'not_started', 'critical', 'medium',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '20-28h', 'high',
 'Can generate CRUD endpoints, data models, and sync logic',
 ARRAY['Node.js', 'PostgreSQL', 'Zoho API'],
 ARRAY['API Integration', 'Database/SQL'],
 ARRAY['GET /deals with pagination and filters', 'GET /deals/:id with full details', 'GET /deals/stats with aggregations', 'GET /opportunities with installer filter', 'Real-time sync with Zoho CRM', 'Stage change timestamps captured'],
 ARRAY[]::text[],
 ARRAY[]::text[],
 false, true, 5),

((SELECT id FROM projects WHERE slug = 'unified-data-layer'),
 'Calls & Qualifications Endpoints',
 'Build endpoints for Calls and Qualifications data. Integrate with Aircall for call data. Support transcription storage.',
 'development', 'not_started', 'high', 'medium',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '16-24h', 'medium',
 'Can generate API integration code and data models',
 ARRAY['Node.js', 'PostgreSQL', 'Aircall API'],
 ARRAY['API Integration', 'Database/SQL', 'External APIs'],
 ARRAY['GET /calls with pagination and date filters', 'GET /calls/:id with recording URL', 'Call transcripts stored and searchable', 'GET /qualifications with deal linkage', 'Aircall webhook integration working'],
 ARRAY[]::text[],
 ARRAY[]::text[],
 false, false, 6),

((SELECT id FROM projects WHERE slug = 'unified-data-layer'),
 'WhatsApp Conversation History',
 'Build endpoints for WhatsApp conversation history. Integrate with Woztell API to pull full message history per deal.',
 'development', 'not_started', 'high', 'hard',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '20-30h', 'medium',
 'Can help with data mapping and pagination handling',
 ARRAY['Node.js', 'PostgreSQL', 'Woztell API'],
 ARRAY['API Integration', 'Database/SQL', 'External APIs'],
 ARRAY['GET /deals/:id/messages with full history', 'Message direction (inbound/outbound) tracked', 'Timestamps accurate to the second', 'Media attachments referenced', 'Webhook for real-time updates'],
 ARRAY[]::text[],
 ARRAY['Woztell API documentation'],
 true, false, 7),

((SELECT id FROM projects WHERE slug = 'unified-data-layer'),
 'Installers & Regions Endpoints',
 'Build endpoints for Installers and Regions data. Include performance metrics, capacity, and geographic coverage.',
 'development', 'not_started', 'high', 'medium',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '12-18h', 'high',
 'Can generate CRUD endpoints and relationship models',
 ARRAY['Node.js', 'PostgreSQL'],
 ARRAY['API Integration', 'Database/SQL'],
 ARRAY['GET /installers with active/inactive filter', 'GET /installers/:id with regions and metrics', 'GET /regions with postal code coverage', 'Installer capacity and quota tracking', 'Performance metrics per installer'],
 ARRAY[]::text[],
 ARRAY[]::text[],
 false, true, 8),

-- Testing Phase
((SELECT id FROM projects WHERE slug = 'unified-data-layer'),
 'API Testing & Quality Assurance',
 'Comprehensive testing of all API endpoints. Load testing, security audit, edge case handling. Fix bugs and optimize performance.',
 'testing', 'not_started', 'critical', 'medium',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '16-24h', 'high',
 'Can generate test cases, mocks, and load test scripts',
 ARRAY['Jest', 'Postman', 'Load testing tools'],
 ARRAY['API Integration', 'Security/Auth', 'DevOps'],
 ARRAY['Unit tests for all endpoints (>80% coverage)', 'Integration tests passing', 'Load test: handles 100 req/s', 'Security audit completed', 'No critical/high bugs', 'Response times <500ms for 95% of requests'],
 ARRAY[]::text[],
 ARRAY[]::text[],
 false, true, 9),

-- Training Phase
((SELECT id FROM projects WHERE slug = 'unified-data-layer'),
 'API Documentation & Developer Guide',
 'Create comprehensive API documentation with examples. Build interactive API explorer. Write developer onboarding guide.',
 'training', 'not_started', 'high', 'easy',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '12-16h', 'high',
 'Can generate documentation from OpenAPI spec and code comments',
 ARRAY['Swagger/OpenAPI', 'Documentation platform'],
 ARRAY['Training & Documentation', 'API Integration'],
 ARRAY['Interactive API documentation live', 'All endpoints documented with examples', 'Authentication guide complete', 'Error code reference', 'Developer quickstart guide', 'Postman collection published'],
 ARRAY[]::text[],
 ARRAY[]::text[],
 false, true, 10),

-- Rollout Phase
((SELECT id FROM projects WHERE slug = 'unified-data-layer'),
 'Production Deployment & Monitoring',
 'Deploy API to production. Set up monitoring, alerting, and dashboards. Configure backup and disaster recovery.',
 'rollout', 'not_started', 'critical', 'medium',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '8-12h', 'medium',
 'Can help with deployment configs and monitoring setup',
 ARRAY['Vercel/Railway', 'Monitoring tools', 'Alerting'],
 ARRAY['DevOps', 'Security/Auth'],
 ARRAY['API live in production', 'Health check endpoint responding', 'Monitoring dashboard configured', 'Alerts set for errors and latency', 'Database backups scheduled', 'Runbook for incident response'],
 ARRAY['99.9% uptime', '<200ms avg response time', 'Zero data loss'],
 ARRAY[]::text[],
 false, true, 11),

-- Monitoring Phase
((SELECT id FROM projects WHERE slug = 'unified-data-layer'),
 'Ongoing Maintenance & Iteration',
 'Establish ongoing maintenance process. Weekly review of API health, performance optimization, bug fixes, and feature requests.',
 'monitoring', 'not_started', 'medium', 'easy',
 (SELECT id FROM teams WHERE slug = 'technology'),
 'Ongoing (4h/week)', 'medium',
 'Can help analyze logs, identify patterns, and suggest optimizations',
 ARRAY['Monitoring tools', 'Issue tracker'],
 ARRAY['DevOps', 'Stakeholder Management'],
 ARRAY['Weekly health review process established', 'SLA monitoring in place', 'Feature request backlog maintained', 'Incident response process documented'],
 ARRAY['API health score >95%', 'All critical bugs fixed within 24h'],
 ARRAY[]::text[],
 false, false, 12);

-- ============================================================================
-- REPORTING HUB TASKS
-- ============================================================================

INSERT INTO tasks (project_id, title, description, phase, status, priority, difficulty, owner_team_id, estimated_hours, ai_potential, ai_assist_description, tools_needed, knowledge_areas, acceptance_criteria, success_metrics, risks, is_foundational, is_critical_path, order_index)
VALUES
((SELECT id FROM projects WHERE slug = 'reporting-hub'),
 'KPI Discovery & Stakeholder Alignment',
 'Meet with all department heads to understand reporting needs. Define KPIs, formulas, and success thresholds. Get sign-off on metrics definitions.',
 'discovery', 'not_started', 'high', 'medium',
 (SELECT id FROM teams WHERE slug = 'operations'),
 '12-16h', 'medium',
 'Can suggest industry-standard KPIs and help document formulas',
 ARRAY['Meeting tools', 'Notion', 'Spreadsheets'],
 ARRAY['Stakeholder Management', 'Data Analytics', 'Business Logic'],
 ARRAY['KPI catalog with definitions approved by stakeholders', 'Formulas documented and validated', 'Thresholds defined (good/warning/critical)', 'Data sources identified for each KPI', 'Reporting frequency agreed (real-time, daily, weekly)'],
 ARRAY[]::text[],
 ARRAY['Conflicting priorities between departments', 'Undefined metrics'],
 false, true, 0),

((SELECT id FROM projects WHERE slug = 'reporting-hub'),
 'Current State Analysis',
 'Audit existing reports and dashboards. Identify manual reporting processes that can be automated. Document pain points and gaps.',
 'discovery', 'not_started', 'medium', 'easy',
 (SELECT id FROM teams WHERE slug = 'operations'),
 '8-12h', 'medium',
 'Can help analyze and categorize existing reports',
 ARRAY['Existing tools', 'Documentation'],
 ARRAY['Data Analytics', 'Process Design'],
 ARRAY['Inventory of all existing reports', 'Time spent on manual reporting quantified', 'Pain points documented', 'Automation opportunities identified'],
 ARRAY[]::text[],
 ARRAY[]::text[],
 false, false, 1),

((SELECT id FROM projects WHERE slug = 'reporting-hub'),
 'Dashboard Design & Wireframes',
 'Design dashboard layouts, information hierarchy, and user flows. Create wireframes for each stakeholder view. Get design approval.',
 'planning', 'not_started', 'high', 'medium',
 (SELECT id FROM teams WHERE slug = 'product'),
 '12-16h', 'medium',
 'Can suggest dashboard layouts and best practices',
 ARRAY['Figma', 'Wireframing tools'],
 ARRAY['UX Design', 'Data Analytics'],
 ARRAY['Wireframes for executive dashboard', 'Wireframes for department-specific views', 'Mobile-responsive design considered', 'Design approved by key stakeholders'],
 ARRAY[]::text[],
 ARRAY[]::text[],
 false, false, 2),

((SELECT id FROM projects WHERE slug = 'reporting-hub'),
 'Data Pipeline Architecture',
 'Design data pipeline for KPI calculations. Define aggregation schedules, caching strategy, and historical data retention.',
 'planning', 'not_started', 'critical', 'hard',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '8-12h', 'high',
 'Can help design data models and aggregation logic',
 ARRAY['Architecture tools', 'Documentation'],
 ARRAY['Database/SQL', 'Data Analytics', 'DevOps'],
 ARRAY['Data pipeline architecture documented', 'Aggregation schedules defined', 'Caching strategy for real-time KPIs', 'Historical data retention policy', 'API endpoints defined for dashboard'],
 ARRAY[]::text[],
 ARRAY[]::text[],
 true, true, 3),

((SELECT id FROM projects WHERE slug = 'reporting-hub'),
 'KPI Calculation Engine',
 'Build backend service for computing KPIs. Implement aggregations, calculations, and caching. Create API endpoints for dashboard.',
 'development', 'not_started', 'critical', 'hard',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '24-32h', 'high',
 'Can generate SQL queries, aggregation logic, and API handlers',
 ARRAY['Node.js', 'PostgreSQL', 'Redis'],
 ARRAY['Database/SQL', 'Data Analytics', 'API Integration'],
 ARRAY['All KPIs calculating correctly', 'Real-time KPIs updating within 5 seconds', 'Historical snapshots stored daily', 'API endpoints returning correct data', 'Performance: calculations complete in <2s'],
 ARRAY[]::text[],
 ARRAY[]::text[],
 false, true, 4),

((SELECT id FROM projects WHERE slug = 'reporting-hub'),
 'Dashboard Frontend Development',
 'Build React dashboard with charts, tables, and filters. Implement responsive design and real-time updates.',
 'development', 'not_started', 'critical', 'medium',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '32-40h', 'high',
 'Can generate chart components, layouts, and styling',
 ARRAY['React', 'Recharts/Chart.js', 'Tailwind'],
 ARRAY['Frontend/React', 'UX Design', 'Data Analytics'],
 ARRAY['Executive dashboard complete', 'Department views implemented', 'Charts rendering correctly', 'Filters and date ranges working', 'Mobile responsive', 'Real-time updates functioning'],
 ARRAY[]::text[],
 ARRAY[]::text[],
 true, true, 5),

((SELECT id FROM projects WHERE slug = 'reporting-hub'),
 'Export & Scheduling Features',
 'Add PDF/Excel export functionality. Implement scheduled email reports with customizable frequency.',
 'development', 'not_started', 'medium', 'medium',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '12-16h', 'high',
 'Can generate PDF templates and scheduling logic',
 ARRAY['React-PDF', 'Node-cron', 'SendGrid'],
 ARRAY['Frontend/React', 'DevOps', 'API Integration'],
 ARRAY['PDF export working for all dashboards', 'Excel export with proper formatting', 'Scheduled reports configurable', 'Email delivery reliable'],
 ARRAY[]::text[],
 ARRAY[]::text[],
 false, false, 6),

((SELECT id FROM projects WHERE slug = 'reporting-hub'),
 'Data Validation & UAT',
 'Validate KPI calculations against manual calculations. Conduct user acceptance testing with stakeholders. Fix discrepancies.',
 'testing', 'not_started', 'critical', 'medium',
 (SELECT id FROM teams WHERE slug = 'operations'),
 '16-24h', 'medium',
 'Can help generate test cases and validation scripts',
 ARRAY['Spreadsheets', 'Testing tools'],
 ARRAY['Data Analytics', 'Business Logic'],
 ARRAY['All KPIs validated against source data', 'Finance sign-off on financial metrics', 'Sales sign-off on pipeline metrics', 'No calculation discrepancies', 'UAT sign-off from all stakeholders'],
 ARRAY[]::text[],
 ARRAY['Discrepancies between systems', 'Stakeholder availability for UAT'],
 false, true, 7),

((SELECT id FROM projects WHERE slug = 'reporting-hub'),
 'Training & Documentation',
 'Create user guides and video tutorials. Conduct training sessions for each department. Document KPI definitions and interpretations.',
 'training', 'not_started', 'high', 'easy',
 (SELECT id FROM teams WHERE slug = 'operations'),
 '12-16h', 'high',
 'Can generate documentation and training materials',
 ARRAY['Documentation', 'Video recording', 'Training tools'],
 ARRAY['Training & Documentation', 'Change Management'],
 ARRAY['User guide published', 'Video tutorials recorded', 'Training sessions completed', 'KPI glossary published', 'FAQ documented'],
 ARRAY[]::text[],
 ARRAY[]::text[],
 false, false, 8),

((SELECT id FROM projects WHERE slug = 'reporting-hub'),
 'Production Launch & Adoption',
 'Deploy to production. Announce to company. Monitor adoption and gather feedback. Iterate based on user input.',
 'rollout', 'not_started', 'critical', 'easy',
 (SELECT id FROM teams WHERE slug = 'operations'),
 '8-12h', 'low',
 'Human change management required',
 ARRAY['Communication tools', 'Analytics'],
 ARRAY['Change Management', 'Stakeholder Management'],
 ARRAY['Dashboard live in production', 'Company announcement sent', 'Adoption tracking in place', 'Feedback channel established', 'First week issues resolved'],
 ARRAY['80% of target users accessing weekly', 'Manual reporting time reduced by 60%'],
 ARRAY[]::text[],
 false, true, 9);

-- ============================================================================
-- SDR PORTAL TASKS
-- ============================================================================

INSERT INTO tasks (project_id, title, description, phase, status, priority, difficulty, owner_team_id, estimated_hours, ai_potential, ai_assist_description, tools_needed, knowledge_areas, acceptance_criteria, success_metrics, risks, is_foundational, is_critical_path, order_index)
VALUES
((SELECT id FROM projects WHERE slug = 'sdr-portal'),
 'SDR Workflow Analysis & Pain Points',
 'Shadow SDR team for a full week. Document current workflow, tools used, time spent on each activity. Identify pain points and inefficiencies.',
 'discovery', 'not_started', 'high', 'easy',
 (SELECT id FROM teams WHERE slug = 'operations'),
 '16-20h', 'low',
 'Human observation required for authentic workflow understanding',
 ARRAY['Observation', 'Documentation'],
 ARRAY['Process Design', 'Stakeholder Management'],
 ARRAY['Complete SDR workflow documented', 'Time breakdown by activity', 'Pain points ranked by impact', 'Tool usage mapped', 'Improvement opportunities identified'],
 ARRAY[]::text[],
 ARRAY['SDR availability', 'Biased self-reporting'],
 false, true, 0),

((SELECT id FROM projects WHERE slug = 'sdr-portal'),
 'Competitive Tool Analysis',
 'Research competitor SDR tools (Salesloft, Outreach, etc.). Identify best practices and features to incorporate.',
 'discovery', 'not_started', 'medium', 'easy',
 (SELECT id FROM teams WHERE slug = 'product'),
 '8-12h', 'high',
 'Can help research and summarize competitor features',
 ARRAY['Research', 'Demo accounts'],
 ARRAY['UX Design', 'Business Logic'],
 ARRAY['Competitor feature matrix created', 'Best practices documented', 'Features prioritized for Abeto context'],
 ARRAY[]::text[],
 ARRAY[]::text[],
 false, false, 1),

((SELECT id FROM projects WHERE slug = 'sdr-portal'),
 'AI Use Cases Definition',
 'Define specific AI use cases: conversation summaries, prioritization, scripts, objection handling. Get SDR team input on most valuable.',
 'discovery', 'not_started', 'high', 'medium',
 (SELECT id FROM teams WHERE slug = 'operations'),
 '8-12h', 'medium',
 'Can suggest AI use cases and help design prompts',
 ARRAY['Workshops', 'Documentation'],
 ARRAY['LLM/Prompt Engineering', 'Business Logic'],
 ARRAY['AI use cases documented with expected impact', 'SDR team buy-in achieved', 'Priority ranking agreed', 'Success metrics defined per use case'],
 ARRAY[]::text[],
 ARRAY[]::text[],
 false, true, 2),

((SELECT id FROM projects WHERE slug = 'sdr-portal'),
 'Portal UX Design & Prototyping',
 'Design portal layout, information architecture, and key screens. Create clickable prototype. User test with SDRs.',
 'planning', 'not_started', 'high', 'medium',
 (SELECT id FROM teams WHERE slug = 'product'),
 '16-24h', 'medium',
 'Can suggest layouts and help with design patterns',
 ARRAY['Figma', 'Prototyping tools'],
 ARRAY['UX Design', 'Frontend/React'],
 ARRAY['Wireframes for all key screens', 'Clickable prototype created', 'User testing completed with 3+ SDRs', 'Feedback incorporated', 'Final design approved'],
 ARRAY[]::text[],
 ARRAY[]::text[],
 false, true, 3),

((SELECT id FROM projects WHERE slug = 'sdr-portal'),
 'Contact Queue & Prioritization',
 'Build smart contact queue with AI prioritization. Show next best contact with reasoning. Implement filters and manual override.',
 'development', 'not_started', 'critical', 'hard',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '24-32h', 'high',
 'Can help build prioritization algorithm and UI components',
 ARRAY['React', 'Node.js', 'PostgreSQL'],
 ARRAY['Frontend/React', 'API Integration', 'AI/ML'],
 ARRAY['Contact queue displays prioritized leads', 'AI reasoning shown for each lead', 'Filters working (region, installer, stage)', 'Manual priority override available', 'Real-time updates from API'],
 ARRAY['SDR contact rate +20%'],
 ARRAY['AI accuracy concerns'],
 false, true, 4),

((SELECT id FROM projects WHERE slug = 'sdr-portal'),
 'WhatsApp Summary Integration',
 'Integrate AI-generated conversation summaries. Show key points, sentiment, and suggested talking points for each lead.',
 'development', 'not_started', 'critical', 'hard',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '20-28h', 'high',
 'Core AI feature - can help with prompt engineering and integration',
 ARRAY['Claude/OpenAI API', 'React', 'Node.js'],
 ARRAY['LLM/Prompt Engineering', 'Frontend/React', 'API Integration'],
 ARRAY['Summaries generated for all leads with conversations', 'Key points extracted', 'Sentiment analysis displayed', 'Suggested talking points shown', 'Summary refresh on demand'],
 ARRAY['Call prep time reduced by 50%'],
 ARRAY['AI accuracy', 'API costs'],
 false, true, 5),

((SELECT id FROM projects WHERE slug = 'sdr-portal'),
 'Call Logging & Outcome Tracking',
 'Build call logging interface with quick outcome selection. Integrate with Aircall for automatic call duration tracking.',
 'development', 'not_started', 'high', 'medium',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '16-24h', 'medium',
 'Can help build forms and Aircall integration',
 ARRAY['React', 'Aircall API', 'Zoho API'],
 ARRAY['Frontend/React', 'API Integration'],
 ARRAY['Quick outcome logging (1-click)', 'Notes field with auto-save', 'Call duration auto-populated', 'Next action scheduling', 'Sync to Zoho CRM'],
 ARRAY['100% call outcome capture'],
 ARRAY[]::text[],
 false, false, 6),

((SELECT id FROM projects WHERE slug = 'sdr-portal'),
 'Performance Dashboard',
 'Build SDR performance dashboard showing daily/weekly metrics, leaderboard, and goal progress.',
 'development', 'not_started', 'medium', 'medium',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '16-20h', 'high',
 'Can help build chart components and metrics calculations',
 ARRAY['React', 'Recharts', 'PostgreSQL'],
 ARRAY['Frontend/React', 'Data Analytics'],
 ARRAY['Daily metrics displayed', 'Weekly trends visible', 'Goal progress tracking', 'Team leaderboard', 'Personal performance history'],
 ARRAY[]::text[],
 ARRAY[]::text[],
 false, false, 7),

((SELECT id FROM projects WHERE slug = 'sdr-portal'),
 'Portal Testing & QA',
 'Comprehensive testing of all portal features. Performance testing, mobile responsiveness, edge case handling.',
 'testing', 'not_started', 'critical', 'medium',
 (SELECT id FROM teams WHERE slug = 'technology'),
 '12-16h', 'medium',
 'Can help generate test cases',
 ARRAY['Testing tools', 'Mobile devices'],
 ARRAY['Frontend/React', 'DevOps'],
 ARRAY['All features tested', 'Mobile responsive', 'Performance acceptable (<2s load)', 'Edge cases handled', 'No critical bugs'],
 ARRAY[]::text[],
 ARRAY[]::text[],
 false, true, 8),

((SELECT id FROM projects WHERE slug = 'sdr-portal'),
 'SDR Training & Onboarding',
 'Create training materials. Conduct hands-on training with SDR team. Gather initial feedback and iterate.',
 'training', 'not_started', 'high', 'easy',
 (SELECT id FROM teams WHERE slug = 'operations'),
 '12-16h', 'medium',
 'Can help create training materials',
 ARRAY['Training tools', 'Video recording'],
 ARRAY['Training & Documentation', 'Change Management'],
 ARRAY['Training guide complete', 'All SDRs trained', 'FAQ documented', 'Feedback collected', 'Quick reference card created'],
 ARRAY['100% SDR adoption'],
 ARRAY['Resistance to change'],
 false, true, 9),

((SELECT id FROM projects WHERE slug = 'sdr-portal'),
 'Production Launch & Monitoring',
 'Deploy to production. Roll out to SDR team. Monitor usage and performance. Address issues quickly.',
 'rollout', 'not_started', 'critical', 'easy',
 (SELECT id FROM teams WHERE slug = 'operations'),
 '8-12h', 'low',
 'Human change management required',
 ARRAY['Deployment tools', 'Analytics'],
 ARRAY['Change Management', 'DevOps'],
 ARRAY['Portal live in production', 'All SDRs have access', 'Usage tracking active', 'Support channel established', 'First week issues resolved'],
 ARRAY['90% daily active usage'],
 ARRAY[]::text[],
 false, true, 10);

-- Re-enable RLS
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;

-- Verification
SELECT
  p.title as project,
  COUNT(t.id) as task_count
FROM projects p
LEFT JOIN tasks t ON t.project_id = p.id
GROUP BY p.title
ORDER BY task_count DESC
LIMIT 10;
