// Migration script to populate Supabase with all projects and tasks from API dashboard
// Run with: npx ts-node scripts/migrate-data.ts

import { createClient } from '@supabase/supabase-js';

const supabaseUrl = 'https://pyxjwtyvmbltscayabsj.supabase.co';
const supabaseServiceKey = process.env.SUPABASE_SERVICE_KEY || '';

const supabase = createClient(supabaseUrl, supabaseServiceKey);

// ============================================================================
// PROJECTS DATA (from abeto-api-dashboard)
// ============================================================================

const projects = [
  {
    title: 'Unified Data Layer',
    slug: 'unified-data-layer',
    description: 'Central API that aggregates all data sources (Zoho, Woztell, Aircall, Holded) into a unified, consistent interface.',
    why_it_matters: 'Foundation for all other projects. Without clean, unified data, nothing else works properly.',
    pillar: 'Data Foundation',
    category: 'Data Infrastructure',
    status: 'in_progress',
    priority: 'critical',
    difficulty: 'hard',
    owner_team: 'Technology',
    estimated_hours_min: 180,
    estimated_hours_max: 240,
  },
  {
    title: 'Reporting Hub',
    slug: 'reporting-hub',
    description: 'Centralized reporting dashboard with automated weekly digests, provider ROI analysis, and performance metrics.',
    why_it_matters: 'Gives leadership visibility into operations without manual report generation.',
    pillar: 'Knowledge Generation',
    category: 'Analytics',
    status: 'planning',
    priority: 'high',
    difficulty: 'medium',
    owner_team: 'Operations',
    estimated_hours_min: 100,
    estimated_hours_max: 140,
  },
  {
    title: 'SDR Portal',
    slug: 'sdr-portal',
    description: 'Dedicated portal for SDRs with prioritized contact lists, WhatsApp summaries, AI qualification notes, and call prep tools.',
    why_it_matters: 'Empowers SDRs to work more efficiently and make better contact decisions.',
    pillar: 'Human Empowerment',
    category: 'Sales Tools',
    status: 'in_progress',
    priority: 'critical',
    difficulty: 'hard',
    owner_team: 'Technology',
    estimated_hours_min: 150,
    estimated_hours_max: 200,
  },
  {
    title: 'Installer Portal & Product',
    slug: 'installer-portal-product',
    description: 'Self-service portal for installers to manage leads, submit quotes, provide feedback, and track performance.',
    why_it_matters: 'Reduces ops overhead and gives installers ownership of their pipeline.',
    pillar: 'Human Empowerment',
    category: 'Partner Tools',
    status: 'planning',
    priority: 'high',
    difficulty: 'hard',
    owner_team: 'Technology',
    estimated_hours_min: 160,
    estimated_hours_max: 220,
  },
  {
    title: 'AI Cortex',
    slug: 'ai-cortex',
    description: 'Central AI/ML platform for lead scoring, conversation analysis, qualification automation, and predictive insights.',
    why_it_matters: 'Leverages AI to augment human decision-making across all touchpoints.',
    pillar: 'Knowledge Generation',
    category: 'AI/ML',
    status: 'idea',
    priority: 'high',
    difficulty: 'hard',
    owner_team: 'Technology',
    estimated_hours_min: 200,
    estimated_hours_max: 280,
  },
  {
    title: 'Campaign OS',
    slug: 'campaign-os',
    description: 'Lead provider management system with ROI tracking, validation automation, and performance optimization.',
    why_it_matters: 'Optimizes marketing spend by identifying best-performing lead sources.',
    pillar: 'Knowledge Generation',
    category: 'Marketing',
    status: 'planning',
    priority: 'high',
    difficulty: 'medium',
    owner_team: 'Marketing',
    estimated_hours_min: 100,
    estimated_hours_max: 140,
  },
  {
    title: 'Data Quality Monitor',
    slug: 'data-quality-monitor',
    description: 'Real-time monitoring of data quality across all systems with alerts for anomalies and degradation.',
    why_it_matters: 'Ensures data integrity and catches issues before they impact operations.',
    pillar: 'Data Foundation',
    category: 'Data Infrastructure',
    status: 'idea',
    priority: 'medium',
    difficulty: 'medium',
    owner_team: 'Technology',
    estimated_hours_min: 60,
    estimated_hours_max: 90,
  },
  {
    title: 'Funnel Automation OS',
    slug: 'funnel-automation-os',
    description: 'Automated lead nurturing flows via WhatsApp and email based on lead behavior and stage.',
    why_it_matters: 'Increases contact rates and conversions through timely, relevant outreach.',
    pillar: 'Human Empowerment',
    category: 'Automation',
    status: 'planning',
    priority: 'high',
    difficulty: 'medium',
    owner_team: 'Operations',
    estimated_hours_min: 120,
    estimated_hours_max: 160,
  },
  {
    title: 'Partner Expansion Tool',
    slug: 'partner-expansion-tool',
    description: 'CRM and outreach automation for recruiting new installer partners.',
    why_it_matters: 'Scales installer network to handle growth in lead volume.',
    pillar: 'Human Empowerment',
    category: 'Partner Tools',
    status: 'idea',
    priority: 'medium',
    difficulty: 'medium',
    owner_team: 'Sales',
    estimated_hours_min: 120,
    estimated_hours_max: 160,
  },
  {
    title: 'Investor Portal',
    slug: 'investor-portal',
    description: 'Secure portal for investors with real-time KPIs, document room, and AI Q&A.',
    why_it_matters: 'Reduces investor reporting overhead and provides transparency.',
    pillar: 'Human Empowerment',
    category: 'Finance',
    status: 'idea',
    priority: 'low',
    difficulty: 'medium',
    owner_team: 'Finance',
    estimated_hours_min: 100,
    estimated_hours_max: 140,
  },
  {
    title: 'Installer Performance Tracking',
    slug: 'installer-performance-tracking',
    description: 'Dashboard and alerting for installer SLAs, conversion rates, and quality metrics.',
    why_it_matters: 'Identifies underperforming installers and rewards top performers.',
    pillar: 'Knowledge Generation',
    category: 'Analytics',
    status: 'planning',
    priority: 'high',
    difficulty: 'medium',
    owner_team: 'Operations',
    estimated_hours_min: 90,
    estimated_hours_max: 120,
  },
  {
    title: 'Dynamic Allocation Engine',
    slug: 'dynamic-allocation-engine',
    description: 'Real-time lead-to-installer matching based on capacity, performance, and geography.',
    why_it_matters: 'Maximizes conversion by matching leads with best-fit installers.',
    pillar: 'Knowledge Generation',
    category: 'Automation',
    status: 'idea',
    priority: 'high',
    difficulty: 'hard',
    owner_team: 'Technology',
    estimated_hours_min: 140,
    estimated_hours_max: 180,
  },
  {
    title: 'WhatsApp Conversation Summary',
    slug: 'whatsapp-conversation-summary',
    description: 'AI-powered summaries of WhatsApp conversations for SDR call prep.',
    why_it_matters: 'Saves SDR time and improves call quality with context.',
    pillar: 'Knowledge Generation',
    category: 'AI/ML',
    status: 'idea',
    priority: 'medium',
    difficulty: 'medium',
    owner_team: 'Technology',
    estimated_hours_min: 60,
    estimated_hours_max: 80,
  },
  {
    title: 'Contact Prioritization Engine',
    slug: 'contact-prioritization-engine',
    description: 'Scoring algorithm to prioritize which leads to contact first based on conversion likelihood.',
    why_it_matters: 'Focuses SDR effort on highest-potential leads.',
    pillar: 'Knowledge Generation',
    category: 'AI/ML',
    status: 'idea',
    priority: 'high',
    difficulty: 'hard',
    owner_team: 'Technology',
    estimated_hours_min: 80,
    estimated_hours_max: 110,
  },
  {
    title: 'Lead Recycling Workflow',
    slug: 'lead-recycling-workflow',
    description: 'Automated re-engagement of lost leads based on timing and reason for loss.',
    why_it_matters: 'Recovers value from leads that would otherwise be wasted.',
    pillar: 'Human Empowerment',
    category: 'Automation',
    status: 'idea',
    priority: 'medium',
    difficulty: 'medium',
    owner_team: 'Operations',
    estimated_hours_min: 70,
    estimated_hours_max: 90,
  },
  {
    title: 'Installer Feedback System',
    slug: 'installer-feedback-system',
    description: 'Structured feedback collection from installers on lead quality.',
    why_it_matters: 'Closes the loop on lead quality and informs provider decisions.',
    pillar: 'Data Foundation',
    category: 'Data Infrastructure',
    status: 'idea',
    priority: 'medium',
    difficulty: 'easy',
    owner_team: 'Operations',
    estimated_hours_min: 50,
    estimated_hours_max: 70,
  },
  {
    title: 'Installer Quote Sync',
    slug: 'installer-quote-sync',
    description: 'Real-time sync of installer quotes back to CRM.',
    why_it_matters: 'Eliminates manual quote entry and provides visibility.',
    pillar: 'Data Foundation',
    category: 'Data Infrastructure',
    status: 'idea',
    priority: 'medium',
    difficulty: 'easy',
    owner_team: 'Technology',
    estimated_hours_min: 45,
    estimated_hours_max: 60,
  },
  {
    title: 'Answer Rate Monitoring',
    slug: 'answer-rate-monitoring',
    description: 'Real-time tracking of call answer rates by segment with alerting.',
    why_it_matters: 'Identifies contact rate issues quickly.',
    pillar: 'Knowledge Generation',
    category: 'Analytics',
    status: 'idea',
    priority: 'low',
    difficulty: 'easy',
    owner_team: 'Operations',
    estimated_hours_min: 40,
    estimated_hours_max: 55,
  },
  {
    title: 'GDPR Compliance Tracker',
    slug: 'gdpr-compliance-tracker',
    description: 'Consent management and data subject rights portal.',
    why_it_matters: 'Ensures legal compliance and avoids fines.',
    pillar: 'Data Foundation',
    category: 'Compliance',
    status: 'idea',
    priority: 'medium',
    difficulty: 'hard',
    owner_team: 'Legal',
    estimated_hours_min: 60,
    estimated_hours_max: 80,
  },
  {
    title: 'Automated Invoicing',
    slug: 'automated-invoicing',
    description: 'Automatic invoice generation based on lead outcomes.',
    why_it_matters: 'Eliminates manual invoicing and reduces errors.',
    pillar: 'Human Empowerment',
    category: 'Finance',
    status: 'idea',
    priority: 'medium',
    difficulty: 'medium',
    owner_team: 'Finance',
    estimated_hours_min: 70,
    estimated_hours_max: 90,
  },
  {
    title: 'API Self-Service Portal',
    slug: 'api-self-service-portal',
    description: 'Developer portal for lead providers to integrate directly.',
    why_it_matters: 'Reduces integration overhead and scales provider onboarding.',
    pillar: 'Data Foundation',
    category: 'Data Infrastructure',
    status: 'idea',
    priority: 'low',
    difficulty: 'hard',
    owner_team: 'Technology',
    estimated_hours_min: 80,
    estimated_hours_max: 100,
  },
  {
    title: 'Programmatic SEO Pages',
    slug: 'programmatic-seo-pages',
    description: 'Auto-generated location and topic pages for organic traffic.',
    why_it_matters: 'Drives free organic leads at scale.',
    pillar: 'Human Empowerment',
    category: 'Marketing',
    status: 'idea',
    priority: 'medium',
    difficulty: 'hard',
    owner_team: 'Marketing',
    estimated_hours_min: 100,
    estimated_hours_max: 130,
  },
  {
    title: 'PVPC Savings Widget',
    slug: 'pvpc-savings-widget',
    description: 'Embeddable widget showing real-time electricity savings.',
    why_it_matters: 'Engages visitors with personalized value prop.',
    pillar: 'Human Empowerment',
    category: 'Marketing',
    status: 'idea',
    priority: 'low',
    difficulty: 'medium',
    owner_team: 'Marketing',
    estimated_hours_min: 35,
    estimated_hours_max: 50,
  },
  {
    title: 'IRPF Calculator',
    slug: 'irpf-calculator',
    description: 'Tax deduction calculator for solar installations.',
    why_it_matters: 'Helps customers understand financial benefits.',
    pillar: 'Human Empowerment',
    category: 'Marketing',
    status: 'idea',
    priority: 'low',
    difficulty: 'easy',
    owner_team: 'Marketing',
    estimated_hours_min: 25,
    estimated_hours_max: 35,
  },
  {
    title: 'GMB Automation',
    slug: 'gmb-automation',
    description: 'Automated Google Business Profile management.',
    why_it_matters: 'Improves local SEO and manages reviews at scale.',
    pillar: 'Human Empowerment',
    category: 'Marketing',
    status: 'idea',
    priority: 'low',
    difficulty: 'medium',
    owner_team: 'Marketing',
    estimated_hours_min: 55,
    estimated_hours_max: 75,
  },
  {
    title: 'Review Generation System',
    slug: 'review-generation-system',
    description: 'Automated review request system post-installation.',
    why_it_matters: 'Builds social proof and improves local rankings.',
    pillar: 'Human Empowerment',
    category: 'Marketing',
    status: 'idea',
    priority: 'low',
    difficulty: 'medium',
    owner_team: 'Marketing',
    estimated_hours_min: 45,
    estimated_hours_max: 60,
  },
  {
    title: 'Competitor Intel Agent',
    slug: 'competitor-intel-agent',
    description: 'Automated monitoring of competitor ads, pricing, and activity.',
    why_it_matters: 'Keeps us informed of market dynamics.',
    pillar: 'Knowledge Generation',
    category: 'Marketing',
    status: 'idea',
    priority: 'low',
    difficulty: 'hard',
    owner_team: 'Marketing',
    estimated_hours_min: 50,
    estimated_hours_max: 70,
  },
  {
    title: 'Robinson Suppressor',
    slug: 'robinson-suppressor',
    description: 'Integration with Robinson List for contact suppression.',
    why_it_matters: 'Ensures legal compliance with do-not-call lists.',
    pillar: 'Data Foundation',
    category: 'Compliance',
    status: 'idea',
    priority: 'medium',
    difficulty: 'medium',
    owner_team: 'Legal',
    estimated_hours_min: 35,
    estimated_hours_max: 50,
  },
  {
    title: 'Unified Quote API',
    slug: 'unified-quote-api',
    description: 'Standardized quote flow across all installer types.',
    why_it_matters: 'Simplifies quote management and improves data quality.',
    pillar: 'Data Foundation',
    category: 'Data Infrastructure',
    status: 'idea',
    priority: 'medium',
    difficulty: 'hard',
    owner_team: 'Technology',
    estimated_hours_min: 80,
    estimated_hours_max: 100,
  },
];

// ============================================================================
// TASKS DATA (sample for key projects - will be expanded)
// ============================================================================

const tasksByProject: Record<string, Array<{
  title: string;
  description: string;
  phase: string;
  owner_team: string;
  estimated_hours: string;
  difficulty: string;
  ai_potential: string;
  ai_assist_description: string;
  tools_needed: string[];
  knowledge_areas: string[];
  acceptance_criteria: string[];
  success_metrics: string[];
  risks: string[];
  is_foundational: boolean;
  is_critical_path: boolean;
}>> = {
  'unified-data-layer': [
    {
      title: 'Data Audit & Gap Analysis',
      description: 'Audit all existing data sources (Zoho, Woztell, Aircall, Holded). Document current data flows, identify gaps, inconsistencies, and missing fields. Create data dictionary.',
      phase: 'discovery',
      owner_team: 'Technology',
      estimated_hours: '16-24h',
      difficulty: 'medium',
      ai_potential: 'medium',
      ai_assist_description: 'Can help analyze data schemas and generate documentation templates',
      tools_needed: ['Notion', 'Spreadsheets', 'Existing system access'],
      knowledge_areas: ['Data Analytics', 'Business Logic'],
      acceptance_criteria: ['Complete inventory of all data sources', 'Data dictionary with field definitions', 'Gap analysis document with prioritized missing data', 'Data flow diagrams for current state'],
      success_metrics: ['100% of data sources documented', 'All critical gaps identified'],
      risks: ['Access delays to production systems', 'Undocumented legacy data'],
      is_foundational: true,
      is_critical_path: true,
    },
    {
      title: 'Stakeholder Requirements Workshop',
      description: 'Conduct workshops with Sales, Ops, Finance, and Leadership to understand data needs. Document use cases, reporting requirements, and pain points.',
      phase: 'discovery',
      owner_team: 'Operations',
      estimated_hours: '8-12h',
      difficulty: 'easy',
      ai_potential: 'low',
      ai_assist_description: 'Can help structure workshop agenda and document outputs',
      tools_needed: ['Meeting tools', 'Notion', 'Whiteboard'],
      knowledge_areas: ['Stakeholder Management', 'Business Logic'],
      acceptance_criteria: ['Workshop conducted with all key stakeholders', 'Requirements document approved by stakeholders', 'Priority ranking of data needs', 'Success criteria defined for each use case'],
      success_metrics: [],
      risks: ['Stakeholder availability', 'Conflicting requirements'],
      is_foundational: false,
      is_critical_path: true,
    },
    {
      title: 'API Architecture Design',
      description: 'Design API architecture including endpoints, authentication, rate limiting, caching strategy. Define data models and relationships. Create technical specification document.',
      phase: 'planning',
      owner_team: 'Technology',
      estimated_hours: '20-30h',
      difficulty: 'hard',
      ai_potential: 'high',
      ai_assist_description: 'Can generate OpenAPI specs, data models, and architecture diagrams',
      tools_needed: ['Architecture tools', 'Documentation'],
      knowledge_areas: ['API Integration', 'Database/SQL', 'Security/Auth'],
      acceptance_criteria: ['OpenAPI specification document', 'Database schema design', 'Authentication flow documented', 'Rate limiting strategy defined'],
      success_metrics: [],
      risks: ['Over-engineering', 'Missing edge cases'],
      is_foundational: true,
      is_critical_path: true,
    },
    {
      title: 'Zoho CRM Integration',
      description: 'Build integration with Zoho CRM for opportunities, contacts, and accounts. Handle pagination, rate limits, and incremental sync.',
      phase: 'development',
      owner_team: 'Technology',
      estimated_hours: '30-40h',
      difficulty: 'hard',
      ai_potential: 'high',
      ai_assist_description: 'Can generate API client code, data transformations, and error handling',
      tools_needed: ['Node.js', 'Zoho API', 'PostgreSQL'],
      knowledge_areas: ['API Integration', 'Database/SQL'],
      acceptance_criteria: ['All opportunity fields syncing', 'Incremental sync working', 'Error handling and retries', 'Audit logging'],
      success_metrics: ['99.9% sync reliability', '<5 min sync delay'],
      risks: ['Zoho API rate limits', 'Data model changes'],
      is_foundational: true,
      is_critical_path: true,
    },
    {
      title: 'Aircall Integration',
      description: 'Integrate Aircall API for call logs, recordings, and transcripts. Build real-time webhook handler.',
      phase: 'development',
      owner_team: 'Technology',
      estimated_hours: '25-35h',
      difficulty: 'hard',
      ai_potential: 'medium',
      ai_assist_description: 'Can generate API integration boilerplate and webhook handlers',
      tools_needed: ['Aircall API', 'Node.js', 'PostgreSQL'],
      knowledge_areas: ['API Integration', 'Database/SQL'],
      acceptance_criteria: ['Call logs syncing', 'Recordings accessible', 'Webhooks processing in real-time'],
      success_metrics: ['All calls captured', 'Real-time webhook latency <1s'],
      risks: ['Aircall API access', 'Webhook reliability'],
      is_foundational: true,
      is_critical_path: false,
    },
    {
      title: 'Woztell WhatsApp Integration',
      description: 'Integrate Woztell API for WhatsApp conversation history, message direction, and timestamps.',
      phase: 'development',
      owner_team: 'Technology',
      estimated_hours: '20-30h',
      difficulty: 'medium',
      ai_potential: 'medium',
      ai_assist_description: 'Can help with data mapping and pagination handling',
      tools_needed: ['Woztell API', 'Node.js', 'PostgreSQL'],
      knowledge_areas: ['API Integration', 'Database/SQL'],
      acceptance_criteria: ['Full conversation history syncing', 'Message direction tracked', 'Timestamps accurate'],
      success_metrics: ['All conversations captured', 'Historical data imported'],
      risks: ['Woztell API documentation', 'Rate limits'],
      is_foundational: true,
      is_critical_path: false,
    },
    {
      title: 'Unit & Integration Testing',
      description: 'Comprehensive test suite for all API endpoints and integrations.',
      phase: 'testing',
      owner_team: 'Technology',
      estimated_hours: '20-25h',
      difficulty: 'medium',
      ai_potential: 'high',
      ai_assist_description: 'Can generate test cases and mock data',
      tools_needed: ['Jest', 'Supertest'],
      knowledge_areas: ['API Integration', 'Database/SQL'],
      acceptance_criteria: ['80% code coverage', 'All critical paths tested', 'Integration tests passing'],
      success_metrics: ['Zero critical bugs in production'],
      risks: ['Test environment stability'],
      is_foundational: false,
      is_critical_path: true,
    },
    {
      title: 'API Documentation',
      description: 'Complete API documentation with examples, authentication guide, and error handling.',
      phase: 'training',
      owner_team: 'Technology',
      estimated_hours: '10-15h',
      difficulty: 'easy',
      ai_potential: 'high',
      ai_assist_description: 'Can generate documentation from OpenAPI spec',
      tools_needed: ['Documentation tools'],
      knowledge_areas: ['API Integration'],
      acceptance_criteria: ['All endpoints documented', 'Examples for each endpoint', 'Authentication guide complete'],
      success_metrics: ['Team can use API without support'],
      risks: [],
      is_foundational: false,
      is_critical_path: false,
    },
    {
      title: 'Production Deployment',
      description: 'Deploy API to production with monitoring, logging, and alerting.',
      phase: 'rollout',
      owner_team: 'Technology',
      estimated_hours: '15-20h',
      difficulty: 'medium',
      ai_potential: 'medium',
      ai_assist_description: 'Can generate deployment scripts and monitoring configs',
      tools_needed: ['AWS/GCP', 'Docker', 'Monitoring tools'],
      knowledge_areas: ['DevOps', 'Security/Auth'],
      acceptance_criteria: ['API deployed to production', 'Monitoring active', 'Alerts configured', 'Rollback plan tested'],
      success_metrics: ['99.9% uptime', '<100ms response time'],
      risks: ['Production stability', 'Data migration'],
      is_foundational: false,
      is_critical_path: true,
    },
    {
      title: 'Performance Monitoring & Optimization',
      description: 'Ongoing monitoring and optimization of API performance.',
      phase: 'monitoring',
      owner_team: 'Technology',
      estimated_hours: 'Ongoing (5h/week)',
      difficulty: 'medium',
      ai_potential: 'medium',
      ai_assist_description: 'Can analyze performance data and suggest optimizations',
      tools_needed: ['Monitoring tools', 'Analytics'],
      knowledge_areas: ['DevOps', 'Database/SQL'],
      acceptance_criteria: ['Weekly performance reviews', 'SLOs met', 'Capacity planning active'],
      success_metrics: ['99.9% uptime', 'Response times within SLA'],
      risks: ['Scaling issues', 'Cost overruns'],
      is_foundational: false,
      is_critical_path: false,
    },
  ],
  'sdr-portal': [
    {
      title: 'SDR Workflow Discovery',
      description: 'Shadow SDRs to understand current workflow, pain points, and time allocation. Document key use cases.',
      phase: 'discovery',
      owner_team: 'Operations',
      estimated_hours: '12-16h',
      difficulty: 'easy',
      ai_potential: 'low',
      ai_assist_description: 'Can help structure findings and identify patterns',
      tools_needed: ['Screen recording', 'Documentation'],
      knowledge_areas: ['Business Logic', 'Process Design'],
      acceptance_criteria: ['Workflow documented', 'Pain points identified', 'Time allocation mapped'],
      success_metrics: [],
      risks: ['SDR availability'],
      is_foundational: false,
      is_critical_path: true,
    },
    {
      title: 'Portal UI/UX Design',
      description: 'Design intuitive interface for SDR daily workflow including contact queue, call prep, and notes.',
      phase: 'planning',
      owner_team: 'Product',
      estimated_hours: '20-30h',
      difficulty: 'medium',
      ai_potential: 'medium',
      ai_assist_description: 'Can generate wireframes and suggest UX patterns',
      tools_needed: ['Figma', 'Design system'],
      knowledge_areas: ['UX Design', 'Frontend/React'],
      acceptance_criteria: ['Wireframes approved', 'Design system applied', 'Mobile-responsive'],
      success_metrics: ['SDR approval of designs'],
      risks: ['Scope creep', 'Conflicting requirements'],
      is_foundational: false,
      is_critical_path: true,
    },
    {
      title: 'Contact Queue Component',
      description: 'Build prioritized contact queue with filtering, sorting, and real-time updates.',
      phase: 'development',
      owner_team: 'Technology',
      estimated_hours: '25-35h',
      difficulty: 'hard',
      ai_potential: 'high',
      ai_assist_description: 'Can generate React components and state management',
      tools_needed: ['React', 'TypeScript', 'API'],
      knowledge_areas: ['Frontend/React', 'API Integration'],
      acceptance_criteria: ['Queue displaying correctly', 'Filters working', 'Real-time updates'],
      success_metrics: ['<500ms load time'],
      risks: ['Performance with large lists'],
      is_foundational: false,
      is_critical_path: true,
    },
    {
      title: 'WhatsApp Summary Integration',
      description: 'Integrate AI-powered WhatsApp conversation summaries in call prep view.',
      phase: 'development',
      owner_team: 'Technology',
      estimated_hours: '15-20h',
      difficulty: 'medium',
      ai_potential: 'high',
      ai_assist_description: 'Can generate LLM prompts and integration code',
      tools_needed: ['LLM API', 'React'],
      knowledge_areas: ['LLM/Prompt Engineering', 'Frontend/React'],
      acceptance_criteria: ['Summaries generating', 'Quality validated', 'Latency acceptable'],
      success_metrics: ['2+ min saved per call prep'],
      risks: ['LLM costs', 'Summary quality'],
      is_foundational: false,
      is_critical_path: false,
    },
    {
      title: 'Call Notes & Outcomes',
      description: 'Build call notes interface with outcome tracking and CRM sync.',
      phase: 'development',
      owner_team: 'Technology',
      estimated_hours: '20-25h',
      difficulty: 'medium',
      ai_potential: 'high',
      ai_assist_description: 'Can generate form components and API handlers',
      tools_needed: ['React', 'Zoho API'],
      knowledge_areas: ['Frontend/React', 'API Integration'],
      acceptance_criteria: ['Notes saving', 'Outcomes syncing to CRM', 'Auto-save working'],
      success_metrics: ['100% outcome capture rate'],
      risks: ['CRM sync reliability'],
      is_foundational: false,
      is_critical_path: false,
    },
    {
      title: 'SDR Pilot Testing',
      description: 'Pilot with 2-3 SDRs to validate usability and gather feedback.',
      phase: 'testing',
      owner_team: 'Operations',
      estimated_hours: '16-24h',
      difficulty: 'easy',
      ai_potential: 'low',
      ai_assist_description: '',
      tools_needed: ['Feedback forms', 'Analytics'],
      knowledge_areas: ['Stakeholder Management'],
      acceptance_criteria: ['Pilot completed', 'Feedback collected', 'Critical issues fixed'],
      success_metrics: ['SDR satisfaction >4/5'],
      risks: ['Pilot disruption to work'],
      is_foundational: false,
      is_critical_path: true,
    },
    {
      title: 'SDR Training',
      description: 'Train all SDRs on using the new portal effectively.',
      phase: 'training',
      owner_team: 'Operations',
      estimated_hours: '8-12h',
      difficulty: 'easy',
      ai_potential: 'medium',
      ai_assist_description: 'Can generate training materials',
      tools_needed: ['Training materials', 'Meeting tools'],
      knowledge_areas: ['Training & Documentation'],
      acceptance_criteria: ['All SDRs trained', 'Documentation complete', 'Q&A session done'],
      success_metrics: ['100% SDR adoption'],
      risks: ['Resistance to change'],
      is_foundational: false,
      is_critical_path: false,
    },
    {
      title: 'Full Team Rollout',
      description: 'Roll out portal to all SDRs and deprecate old workflow.',
      phase: 'rollout',
      owner_team: 'Operations',
      estimated_hours: '10-15h',
      difficulty: 'medium',
      ai_potential: 'low',
      ai_assist_description: '',
      tools_needed: ['Communication tools'],
      knowledge_areas: ['Change Management'],
      acceptance_criteria: ['All SDRs using portal', 'Old workflow deprecated', 'Support process active'],
      success_metrics: ['100% adoption within 2 weeks'],
      risks: ['Adoption resistance', 'Support overload'],
      is_foundational: false,
      is_critical_path: true,
    },
  ],
  'reporting-hub': [
    {
      title: 'Reporting Requirements Discovery',
      description: 'Interview stakeholders to understand reporting needs, frequency, and preferred formats.',
      phase: 'discovery',
      owner_team: 'Operations',
      estimated_hours: '10-15h',
      difficulty: 'easy',
      ai_potential: 'low',
      ai_assist_description: 'Can help structure interview questions',
      tools_needed: ['Meeting tools', 'Documentation'],
      knowledge_areas: ['Stakeholder Management', 'Business Logic'],
      acceptance_criteria: ['All stakeholders interviewed', 'Requirements documented', 'Report types prioritized'],
      success_metrics: [],
      risks: ['Stakeholder availability'],
      is_foundational: false,
      is_critical_path: true,
    },
    {
      title: 'KPI Framework Design',
      description: 'Design comprehensive KPI framework covering all business areas.',
      phase: 'planning',
      owner_team: 'Operations',
      estimated_hours: '15-20h',
      difficulty: 'medium',
      ai_potential: 'medium',
      ai_assist_description: 'Can suggest industry-standard KPIs',
      tools_needed: ['Documentation', 'Spreadsheets'],
      knowledge_areas: ['Data Analytics', 'Business Logic'],
      acceptance_criteria: ['KPIs defined', 'Calculation methods documented', 'Data sources mapped'],
      success_metrics: [],
      risks: ['Metric alignment'],
      is_foundational: true,
      is_critical_path: true,
    },
    {
      title: 'Dashboard Development',
      description: 'Build interactive dashboard with drill-downs and filters.',
      phase: 'development',
      owner_team: 'Technology',
      estimated_hours: '35-45h',
      difficulty: 'hard',
      ai_potential: 'high',
      ai_assist_description: 'Can generate chart components and data queries',
      tools_needed: ['React', 'Chart.js', 'API'],
      knowledge_areas: ['Frontend/React', 'Data Analytics'],
      acceptance_criteria: ['All KPIs displayed', 'Drill-downs working', 'Filters functional'],
      success_metrics: ['<3s load time'],
      risks: ['Data accuracy', 'Performance'],
      is_foundational: false,
      is_critical_path: true,
    },
    {
      title: 'Automated Report Generation',
      description: 'Build automated weekly/monthly report generation and distribution.',
      phase: 'development',
      owner_team: 'Technology',
      estimated_hours: '20-25h',
      difficulty: 'medium',
      ai_potential: 'high',
      ai_assist_description: 'Can generate report templates and scheduling logic',
      tools_needed: ['Node.js', 'PDF generation', 'Email'],
      knowledge_areas: ['API Integration', 'Business Logic'],
      acceptance_criteria: ['Reports generating correctly', 'Distribution working', 'Scheduling flexible'],
      success_metrics: ['100% report delivery rate'],
      risks: ['Email deliverability'],
      is_foundational: false,
      is_critical_path: false,
    },
    {
      title: 'User Acceptance Testing',
      description: 'Test dashboard with end users and gather feedback.',
      phase: 'testing',
      owner_team: 'Operations',
      estimated_hours: '10-15h',
      difficulty: 'easy',
      ai_potential: 'low',
      ai_assist_description: '',
      tools_needed: ['Feedback forms'],
      knowledge_areas: ['Stakeholder Management'],
      acceptance_criteria: ['UAT completed', 'Feedback addressed', 'Sign-off obtained'],
      success_metrics: ['User satisfaction >4/5'],
      risks: ['Scope changes from feedback'],
      is_foundational: false,
      is_critical_path: true,
    },
    {
      title: 'Launch & Monitor',
      description: 'Launch reporting hub and establish review cadence.',
      phase: 'rollout',
      owner_team: 'Operations',
      estimated_hours: '8-12h',
      difficulty: 'easy',
      ai_potential: 'low',
      ai_assist_description: '',
      tools_needed: ['Communication tools'],
      knowledge_areas: ['Change Management'],
      acceptance_criteria: ['Hub live', 'Users onboarded', 'Review cadence established'],
      success_metrics: ['80% weekly active usage'],
      risks: ['Adoption'],
      is_foundational: false,
      is_critical_path: true,
    },
  ],
};

// ============================================================================
// MIGRATION FUNCTIONS
// ============================================================================

async function getPillarId(pillarName: string): Promise<string | null> {
  const { data } = await supabase
    .from('pillars')
    .select('id')
    .eq('name', pillarName)
    .single();
  return data?.id || null;
}

async function getTeamId(teamName: string): Promise<string | null> {
  const { data } = await supabase
    .from('teams')
    .select('id')
    .eq('name', teamName)
    .single();
  return data?.id || null;
}

async function migrateProjects() {
  console.log('Migrating projects...');

  for (const project of projects) {
    const pillarId = await getPillarId(project.pillar);
    const teamId = await getTeamId(project.owner_team);

    const { data, error } = await supabase
      .from('projects')
      .upsert({
        title: project.title,
        slug: project.slug,
        description: project.description,
        why_it_matters: project.why_it_matters,
        pillar_id: pillarId,
        category: project.category,
        status: project.status,
        priority: project.priority,
        difficulty: project.difficulty,
        owner_team_id: teamId,
        estimated_hours_min: project.estimated_hours_min,
        estimated_hours_max: project.estimated_hours_max,
      }, { onConflict: 'slug' })
      .select()
      .single();

    if (error) {
      console.error(`Error migrating project ${project.slug}:`, error);
    } else {
      console.log(`✓ Migrated project: ${project.title}`);

      // Migrate tasks for this project
      const tasks = tasksByProject[project.slug];
      if (tasks && data) {
        await migrateTasks(data.id, tasks);
      }
    }
  }
}

async function migrateTasks(projectId: string, tasks: typeof tasksByProject[string]) {
  for (let i = 0; i < tasks.length; i++) {
    const task = tasks[i];
    const teamId = await getTeamId(task.owner_team);

    const { error } = await supabase
      .from('tasks')
      .insert({
        project_id: projectId,
        title: task.title,
        description: task.description,
        phase: task.phase,
        status: 'not_started',
        difficulty: task.difficulty,
        owner_team_id: teamId,
        estimated_hours: task.estimated_hours,
        ai_potential: task.ai_potential,
        ai_assist_description: task.ai_assist_description,
        tools_needed: task.tools_needed,
        knowledge_areas: task.knowledge_areas,
        acceptance_criteria: task.acceptance_criteria,
        success_metrics: task.success_metrics,
        risks: task.risks,
        is_foundational: task.is_foundational,
        is_critical_path: task.is_critical_path,
        order_index: i,
      });

    if (error) {
      console.error(`  Error migrating task "${task.title}":`, error);
    } else {
      console.log(`  ✓ Task: ${task.title}`);
    }
  }
}

async function main() {
  if (!supabaseServiceKey) {
    console.error('Please set SUPABASE_SERVICE_KEY environment variable');
    console.log('You can find it in Supabase Dashboard > Settings > API > service_role key');
    process.exit(1);
  }

  console.log('Starting migration...\n');
  await migrateProjects();
  console.log('\n✓ Migration complete!');
}

main().catch(console.error);
