-- =============================================================================
-- RICH DATA MIGRATION: Populate projects with comprehensive data
-- This migration syncs all static data from api.ts into Supabase
-- Run this in the Supabase SQL Editor
-- =============================================================================

-- 1. Unified Data Layer (API)
UPDATE projects SET
  human_role_before = 'Data scattered across Zoho, spreadsheets, WhatsApp. Hours spent manually compiling reports.',
  human_role_after = 'Data available instantly via API. Humans focus on decision-making, not data gathering.',
  who_is_empowered = ARRAY['All Teams', 'Developers', 'Operations'],
  new_capabilities = ARRAY['Real-time dashboards', 'Automated reporting', 'AI-powered insights', 'Cross-system integrations'],
  data_required = ARRAY['Zoho CRM access', 'WhatsApp webhooks', 'Telephony events'],
  data_generates = ARRAY['Unified data model', 'Real-time events', 'Historical records'],
  data_improves = ARRAY['Data consistency', 'Access speed', 'Reliability'],
  ops_process = 'All data operations',
  current_loa = 'Automated',
  potential_loa = 'Fully Automated',
  resources_used = ARRAY['Deals', 'Opportunities', 'Calls', 'Qualifications', 'Installers', 'Regions', 'Templates', 'Lost Reasons'],
  api_endpoints = ARRAY['All /internal/* endpoints'],
  prerequisites = ARRAY['Database infrastructure', 'API framework', 'Authentication system'],
  benefits = ARRAY['Single source of truth', 'Real-time data access', 'Foundation for AI/automation', 'Enables all other products'],
  missing_api_data = ARRAY['Call transcripts', 'WhatsApp full history', 'Financial data'],
  integrations_needed = ARRAY['Zoho', 'Woztell', 'Aircall'],
  depends_on = ARRAY[]::text[],
  enables = ARRAY['reporting-hub', 'ai-cortex', 'sdr-portal', 'installer-portal-product'],
  related_to = ARRAY['data-quality-monitor'],
  primary_users = ARRAY['Developers', 'All Products'],
  data_status = 'Live',
  next_milestone = 'Add call transcripts + WhatsApp conversation history',
  problem_statement = 'Data is scattered across Zoho, spreadsheets, and WhatsApp. Teams spend hours manually compiling reports and cannot access real-time information.',
  deliverables = ARRAY['Unified API serving all business data', 'Real-time data synchronization', 'Comprehensive documentation', 'Authentication system']
WHERE slug = 'unified-data-layer';

-- 2. Reporting Hub
UPDATE projects SET
  human_role_before = 'Leadership spends hours in spreadsheets. Different people report different numbers. Decisions based on outdated data.',
  human_role_after = 'Leadership opens one dashboard for truth. Humans focus on analyzing trends and making strategic decisions.',
  who_is_empowered = ARRAY['Leadership', 'Operations', 'Team Leads'],
  new_capabilities = ARRAY['Real-time performance tracking', 'Historical trend analysis', 'Anomaly detection', 'Goal tracking'],
  data_required = ARRAY['Deal pipeline data', 'Opportunity outcomes', 'Call metrics', 'Installer performance'],
  data_generates = ARRAY['KPI snapshots', 'Trend calculations', 'Benchmark comparisons'],
  data_improves = ARRAY['Decision accuracy', 'Goal alignment', 'Team accountability'],
  ops_process = 'Performance Reporting',
  current_loa = 'Manual',
  potential_loa = 'High Automation',
  resources_used = ARRAY['Deals', 'Opportunities', 'Calls', 'Installers', 'Regions'],
  api_endpoints = ARRAY['/internal/deals/stats', '/internal/opportunities/stats', '/internal/calls/stats'],
  prerequisites = ARRAY['KPI definitions agreed', 'Historical data available', 'Dashboard framework'],
  benefits = ARRAY['Single source of truth for KPIs', 'Supports Cortex insights', 'Cross-team visibility', 'Performance benchmarking'],
  missing_api_data = ARRAY['Historical data aggregation', 'Cross-pipeline metrics'],
  integrations_needed = ARRAY['Unified Data Layer'],
  depends_on = ARRAY['unified-data-layer'],
  enables = ARRAY['ai-cortex', 'investor-portal', 'installer-performance-tracking'],
  related_to = ARRAY['data-quality-monitor'],
  primary_users = ARRAY['Leadership', 'Ops'],
  data_status = 'Partial',
  next_milestone = 'Define KPI set + build v1 dashboard',
  problem_statement = 'Leadership spends hours in spreadsheets compiling reports. Different teams report different numbers, leading to confusion and decisions based on outdated data.',
  deliverables = ARRAY['Unified KPI dashboard', 'Real-time metrics tracking', 'Historical trend analysis', 'Automated report generation']
WHERE slug = 'reporting-hub';

-- 3. Data Quality Monitor
UPDATE projects SET
  human_role_before = 'Data issues discovered by accident when reports look wrong. Fire-fighting mode.',
  human_role_after = 'Humans receive proactive alerts about data issues. Focus shifts to prevention and root cause analysis.',
  who_is_empowered = ARRAY['Operations', 'Tech Team', 'Data Stewards'],
  new_capabilities = ARRAY['Proactive issue detection', 'Data lineage tracking', 'Quality scoring', 'Automated remediation'],
  data_required = ARRAY['Access to all data sources', 'Historical baselines'],
  data_generates = ARRAY['Quality scores', 'Freshness metrics', 'Completeness reports', 'Alert history'],
  data_improves = ARRAY['Data reliability', 'Trust in systems', 'Issue response time'],
  ops_process = 'Data governance',
  current_loa = 'Not Implemented',
  potential_loa = 'High Automation',
  resources_used = ARRAY['All resources'],
  api_endpoints = ARRAY['All endpoints'],
  prerequisites = ARRAY['Define quality rules', 'Set up alerting', 'Historical baselines'],
  benefits = ARRAY['Early problem detection', 'Maintains data trust', 'Reduces downstream errors', 'Enables confident automation'],
  missing_api_data = ARRAY['Quality metrics endpoints'],
  integrations_needed = ARRAY['Slack/Email alerts'],
  depends_on = ARRAY['unified-data-layer'],
  enables = ARRAY['ai-cortex'],
  related_to = ARRAY['reporting-hub'],
  primary_users = ARRAY['Ops', 'Tech'],
  data_status = 'None',
  next_milestone = 'Define quality rules + build monitoring dashboard',
  problem_statement = 'Data issues are discovered by accident when reports look wrong. Teams are constantly in fire-fighting mode reacting to problems instead of preventing them.',
  deliverables = ARRAY['Data quality monitoring dashboard', 'Automated alerting system', 'Quality scoring framework', 'Data lineage tracking']
WHERE slug = 'data-quality-monitor';

-- 4. Campaign OS (Lead Generation)
UPDATE projects SET
  human_role_before = 'Marketing manually manages campaigns across platforms. Limited visibility into what works.',
  human_role_after = 'Marketing focuses on creative strategy and market insights. AI handles optimization and scaling.',
  who_is_empowered = ARRAY['Marketing', 'Growth', 'Leadership'],
  new_capabilities = ARRAY['Cross-platform optimization', 'AI creative suggestions', 'Real-time ROI tracking', 'Automated bid management'],
  data_required = ARRAY['UTM tracking', 'Ad platform APIs', 'Conversion data'],
  data_generates = ARRAY['NEW LEADS', 'Campaign performance data', 'Attribution insights', 'Creative performance'],
  data_improves = ARRAY['Lead quality', 'CAC efficiency', 'Channel mix'],
  ops_process = 'Paid Media Optimization',
  current_loa = 'Manual',
  potential_loa = 'High Automation',
  resources_used = ARRAY['Deals', 'Qualifications'],
  api_endpoints = ARRAY['/internal/deals', '/internal/deals/stats'],
  prerequisites = ARRAY['Ad platform APIs (Meta, Google, TikTok)', 'Attribution modeling', 'UTM infrastructure'],
  benefits = ARRAY['Scale lead volume 2-3x', 'Optimization moat via data', 'AI-driven creative angles', 'Cross-platform insights'],
  missing_api_data = ARRAY['UTM tracking', 'Ad spend data', 'Attribution paths'],
  integrations_needed = ARRAY['Meta', 'Google', 'TikTok', 'Zoho'],
  depends_on = ARRAY['unified-data-layer', 'reporting-hub'],
  enables = ARRAY['ai-cortex'],
  related_to = ARRAY['funnel-automation-os'],
  primary_users = ARRAY['Marketing', 'Growth'],
  data_status = 'Static',
  next_milestone = 'Live ad platform sync + automated optimization',
  problem_statement = 'Marketing manually manages campaigns across multiple platforms with limited visibility into what works. No automated optimization or cross-platform insights.',
  deliverables = ARRAY['Multi-platform campaign dashboard', 'AI-powered optimization engine', 'Attribution tracking system', 'Automated bid management']
WHERE slug = 'campaign-os';

-- 5. Partner Expansion Engine
UPDATE projects SET
  human_role_before = 'BizDev manually researches, contacts, and onboards installers. Bottleneck on one person.',
  human_role_after = 'BizDev focuses on relationship building and strategic partnerships. Tool handles prospecting and follow-up.',
  who_is_empowered = ARRAY['BizDev', 'Partner Ops', 'Leadership'],
  new_capabilities = ARRAY['Automated prospecting', 'Engagement scoring', 'Sequence automation', 'Pipeline visibility'],
  data_required = ARRAY['Installer database', 'Region coverage data'],
  data_generates = ARRAY['NEW PARTNERS', 'Prospecting data', 'Engagement history', 'Onboarding records'],
  data_improves = ARRAY['Partner acquisition rate', 'Coverage expansion', 'Onboarding speed'],
  ops_process = 'Installer Network Expansion',
  current_loa = 'Manual',
  potential_loa = 'High Automation',
  resources_used = ARRAY['Installers', 'Regions'],
  api_endpoints = ARRAY['/internal/installers', '/internal/regions'],
  prerequisites = ARRAY['Partner prospect database', 'Email sequences', 'Scoring model'],
  benefits = ARRAY['Remove acquisition bottleneck', '3x partner acquisition rate', 'Systematic geographic expansion', 'No need to scale BDRs'],
  missing_api_data = ARRAY['Partner pipeline tracking', 'Outreach status', 'Engagement scoring'],
  integrations_needed = ARRAY['Email', 'LinkedIn', 'CRM'],
  depends_on = ARRAY['unified-data-layer'],
  enables = ARRAY['installer-portal-product'],
  related_to = ARRAY['installer-performance-tracking'],
  primary_users = ARRAY['Partner Ops', 'BizDev'],
  data_status = 'Static',
  next_milestone = 'Automated outreach sequences + scoring engine',
  problem_statement = 'Partner acquisition is bottlenecked on one person who manually researches, contacts, and onboards installers. Growth is limited by installer capacity.',
  deliverables = ARRAY['Partner prospecting system', 'Automated outreach sequences', 'Engagement scoring model', 'Onboarding workflow automation']
WHERE slug = 'partner-expansion-tool';

-- 6. Funnel Automation OS
UPDATE projects SET
  human_role_before = 'SDRs manually manage every conversation. Limited by hours in the day.',
  human_role_after = 'SDRs focus on complex conversations and closing. Bot handles initial qualification and scheduling.',
  who_is_empowered = ARRAY['SDRs', 'Sales Ops', 'Operations'],
  new_capabilities = ARRAY['24/7 lead response', 'Automated qualification', 'Smart routing', 'A/B testing at scale'],
  data_required = ARRAY['Deal data', 'Message templates', 'Call outcomes'],
  data_generates = ARRAY['NEW CALLS', 'NEW QUALIFICATIONS', 'Conversation data', 'A/B test results'],
  data_improves = ARRAY['Response speed', 'Qualification rate', 'SDR efficiency'],
  ops_process = 'Chatbot + Call Automation',
  current_loa = 'Manual',
  potential_loa = 'High Automation',
  resources_used = ARRAY['Deals', 'Templates', 'Calls'],
  api_endpoints = ARRAY['/internal/deals', '/internal/templates', '/internal/calls'],
  prerequisites = ARRAY['Flow editor', 'Routing engine', 'WhatsApp Business API'],
  benefits = ARRAY['2-3x lead capacity', 'Instant response 24/7', 'Consistent qualification', 'A/B optimization'],
  missing_api_data = ARRAY['Flow state tracking', 'Routing rules', 'A/B test results'],
  integrations_needed = ARRAY['WhatsApp Business', 'Aircall'],
  depends_on = ARRAY['unified-data-layer', 'sdr-portal'],
  enables = ARRAY['ai-cortex'],
  related_to = ARRAY['campaign-os'],
  primary_users = ARRAY['Sales Ops', 'SDR Ops'],
  data_status = 'Static',
  next_milestone = 'Live WhatsApp integration + flow execution',
  problem_statement = 'SDR capacity is the bottleneck. SDRs manually manage every conversation and are limited by hours in the day.',
  deliverables = ARRAY['WhatsApp automation flows', 'Intelligent lead routing', 'Automated qualification bot', 'A/B testing framework']
WHERE slug = 'funnel-automation-os';

-- 7. SDR Portal
UPDATE projects SET
  human_role_before = 'SDRs juggle multiple tabs, manually look up history, guess who to call next.',
  human_role_after = 'SDRs have everything in one view. AI suggests priorities. Humans focus on building relationships and closing.',
  who_is_empowered = ARRAY['SDRs', 'Team Leads', 'Operations'],
  new_capabilities = ARRAY['Single-view workspace', 'AI-suggested priorities', 'Instant context', 'Performance tracking'],
  data_required = ARRAY['All SDR workflow data'],
  data_generates = ARRAY['Activity logs', 'Performance metrics', 'User feedback'],
  data_improves = ARRAY['SDR productivity', 'Data quality', 'Process compliance'],
  ops_process = 'Full SDR Workflow',
  current_loa = 'Semi-Automated',
  potential_loa = 'High Automation',
  resources_used = ARRAY['Deals', 'Qualifications', 'Calls', 'Templates', 'Opportunities'],
  api_endpoints = ARRAY['/internal/deals', '/internal/qualifications', '/internal/calls', '/internal/templates'],
  prerequisites = ARRAY['CRM integration', 'WhatsApp integration', 'Telephony integration'],
  benefits = ARRAY['Single workspace for all SDR tasks', 'AI-powered prioritization', 'Real-time pipeline view', 'Integrated communications'],
  missing_api_data = ARRAY[]::text[],
  integrations_needed = ARRAY['Zoho', 'WhatsApp', 'Aircall'],
  depends_on = ARRAY['unified-data-layer'],
  enables = ARRAY['ai-cortex', 'funnel-automation-os'],
  related_to = ARRAY['reporting-hub'],
  primary_users = ARRAY['SDRs', 'Ops'],
  data_status = 'Live',
  next_milestone = 'Expand Cortex copiloting',
  problem_statement = 'SDRs juggle multiple browser tabs, manually look up history, and guess who to call next. This wastes time and leads to inconsistent customer experiences.',
  deliverables = ARRAY['Unified SDR workspace', 'AI-powered lead prioritization', 'Integrated communications hub', 'Real-time performance dashboard']
WHERE slug = 'sdr-portal';

-- 8. Installer Portal
UPDATE projects SET
  human_role_before = 'Installers call/email to get lead info. No visibility into performance. Frustrated by lack of transparency.',
  human_role_after = 'Installers self-serve all information. Understand their performance. AI helps them prioritize and improve.',
  who_is_empowered = ARRAY['Installers', 'Account Managers', 'Partner Ops'],
  new_capabilities = ARRAY['Self-service lead access', 'Performance dashboards', 'AI recommendations', 'Direct communication'],
  data_required = ARRAY['Installer auth', 'Opportunity data', 'Performance metrics'],
  data_generates = ARRAY['Installer activity logs', 'Feedback data', 'Engagement metrics'],
  data_improves = ARRAY['Installer satisfaction', 'Conversion rates', 'Communication efficiency'],
  ops_process = 'Partner Relationship Management',
  current_loa = 'Not Implemented',
  potential_loa = 'High Automation',
  resources_used = ARRAY['Installers', 'Opportunities', 'Deals', 'Regions', 'Lost Reasons'],
  api_endpoints = ARRAY['/internal/installers', '/internal/opportunities', '/internal/regions/{id}/quotas'],
  prerequisites = ARRAY['Installer authentication', 'Role-based access', 'Performance calculations'],
  benefits = ARRAY['Installer self-service', 'Performance transparency', 'Reduced support burden', 'Happier partners'],
  missing_api_data = ARRAY['Installer auth endpoint', 'Per-installer metrics', 'SLA tracking'],
  integrations_needed = ARRAY['Partner CRM', 'Performance data'],
  depends_on = ARRAY['unified-data-layer', 'reporting-hub'],
  enables = ARRAY['installer-performance-tracking'],
  related_to = ARRAY['partner-expansion-tool'],
  primary_users = ARRAY['Installers', 'Account Managers'],
  data_status = 'None',
  next_milestone = 'Define MVP + pilot with top installers',
  problem_statement = 'Installers call or email to get lead info, have no visibility into their performance, and are frustrated by lack of transparency. This strains partner relationships.',
  deliverables = ARRAY['Installer self-service portal', 'Performance dashboard', 'Lead management interface', 'Communication tools']
WHERE slug = 'installer-portal-product';

-- 9. AI Cortex (Copilot for Everyone)
UPDATE projects SET
  human_role_before = 'Humans make decisions based on intuition and limited data. Context is lost between handoffs.',
  human_role_after = 'Humans make AI-informed decisions. Cortex provides context, suggestions, and handles routine tasks. Humans focus on judgment and relationships.',
  who_is_empowered = ARRAY['Everyone - SDRs, Ops, Leadership, Partners'],
  new_capabilities = ARRAY['Instant context on any lead', 'Proactive suggestions', 'Automated routine decisions', 'Natural language data access'],
  data_required = ARRAY['Complete data foundation', 'Historical patterns', 'User feedback'],
  data_generates = ARRAY['Insights', 'Recommendations', 'Automated actions', 'Learning data'],
  data_improves = ARRAY['Decision quality', 'Response speed', 'Consistency', 'Knowledge sharing'],
  ops_process = 'All processes',
  current_loa = 'Not Implemented',
  potential_loa = 'High Automation',
  resources_used = ARRAY['All resources'],
  api_endpoints = ARRAY['All endpoints'],
  prerequisites = ARRAY['Solid data foundation', 'LLM integration', 'Agent framework'],
  benefits = ARRAY['Compounding intelligence', 'Copilot for all teams', 'Automated routine decisions', 'Institutional memory'],
  missing_api_data = ARRAY['Unified context access', 'Real-time events'],
  integrations_needed = ARRAY['All systems'],
  depends_on = ARRAY['unified-data-layer', 'reporting-hub', 'data-quality-monitor'],
  enables = ARRAY[]::text[],
  related_to = ARRAY['sdr-portal', 'installer-portal-product'],
  primary_users = ARRAY['All teams'],
  data_status = 'None',
  next_milestone = 'MVP in SDR Portal first',
  problem_statement = 'Humans make decisions based on intuition and limited data. Context is lost between handoffs and there is no institutional memory.',
  deliverables = ARRAY['AI copilot integrated across all tools', 'Natural language data interface', 'Proactive suggestion engine', 'Automated routine decision framework']
WHERE slug = 'ai-cortex';

-- 10. Investor Portal
UPDATE projects SET
  human_role_before = 'Leadership spends days preparing board materials. Investors wait for quarterly updates.',
  human_role_after = 'Leadership shares a link. Investors self-serve real-time data. Meetings focus on strategy, not data review.',
  who_is_empowered = ARRAY['Leadership', 'Investors', 'Board Members'],
  new_capabilities = ARRAY['Real-time performance access', 'Self-service data room', 'Automated report generation', 'Cortex Q&A'],
  data_required = ARRAY['KPI data', 'Historical trends', 'Financial metrics'],
  data_generates = ARRAY['Report archives', 'Access logs', 'Q&A history'],
  data_improves = ARRAY['Investor relations', 'Board preparation time', 'Transparency'],
  ops_process = 'Board & Investor Relations',
  current_loa = 'Manual',
  potential_loa = 'High Automation',
  resources_used = ARRAY['Deals', 'Opportunities'],
  api_endpoints = ARRAY['/internal/deals/stats', '/internal/opportunities/stats'],
  prerequisites = ARRAY['Reporting Hub operational', 'Document management', 'Access control'],
  benefits = ARRAY['Professional investor experience', 'Automated reporting', 'Self-service data room', 'AI-powered Q&A'],
  missing_api_data = ARRAY['Financial aggregations', 'Board KPIs'],
  integrations_needed = ARRAY['Reporting Hub'],
  depends_on = ARRAY['unified-data-layer', 'reporting-hub'],
  enables = ARRAY[]::text[],
  related_to = ARRAY['ai-cortex'],
  primary_users = ARRAY['Investors', 'Board', 'Leadership'],
  data_status = 'Partial',
  next_milestone = 'Complete data room + automated reporting',
  problem_statement = 'Leadership spends days preparing board materials. Investors wait for quarterly updates and have no real-time visibility into performance.',
  deliverables = ARRAY['Investor data room', 'Real-time KPI dashboard', 'Automated report generation', 'AI-powered Q&A interface']
WHERE slug = 'investor-portal';

-- 11. Installer Performance & SLA Tracking
UPDATE projects SET
  human_role_before = 'Account managers manually track installer performance in spreadsheets.',
  human_role_after = 'Performance is automatically tracked. Account managers focus on coaching and relationship building.',
  who_is_empowered = ARRAY['Account Managers', 'Partner Ops', 'Installers'],
  new_capabilities = ARRAY['Automated SLA tracking', 'Performance benchmarking', 'Coaching insights', 'Fair allocation'],
  data_required = ARRAY['Opportunity stage timestamps', 'Installer activity'],
  data_generates = ARRAY['Performance scores', 'SLA metrics', 'Conversion rates'],
  data_improves = ARRAY['Installer accountability', 'Lead allocation fairness', 'Coaching effectiveness'],
  ops_process = 'Partner Performance Management',
  current_loa = 'Manual',
  potential_loa = 'High Automation',
  resources_used = ARRAY['Opportunities', 'Installers'],
  api_endpoints = ARRAY['/internal/opportunities', '/internal/opportunities/stats', '/internal/installers'],
  prerequisites = ARRAY['Opportunity timestamps', 'SLA definitions'],
  benefits = ARRAY['Fair performance measurement', 'SLA compliance tracking', 'Data-driven coaching', 'Optimal lead allocation'],
  missing_api_data = ARRAY['Stage timestamps', 'SLA thresholds'],
  integrations_needed = ARRAY['Installer Portal'],
  depends_on = ARRAY['unified-data-layer', 'installer-portal-product'],
  enables = ARRAY['dynamic-allocation-engine'],
  related_to = ARRAY['reporting-hub'],
  primary_users = ARRAY['Account Managers', 'Installers'],
  data_status = 'Partial',
  next_milestone = 'Define SLAs + build tracking',
  problem_statement = 'Account managers manually track installer performance in spreadsheets. There is no systematic way to measure SLA compliance or coach installers.',
  deliverables = ARRAY['Automated performance tracking', 'SLA compliance dashboard', 'Coaching insights tool', 'Fair allocation algorithm']
WHERE slug = 'installer-performance-tracking';

-- 12. Dynamic Lead Allocation Engine
UPDATE projects SET
  human_role_before = 'Ops manually assigns leads using Google Sheets. Time-consuming and inconsistent.',
  human_role_after = 'AI handles routine allocation. Ops reviews edge cases and adjusts rules. Focus shifts to optimization.',
  who_is_empowered = ARRAY['Operations', 'Account Managers'],
  new_capabilities = ARRAY['Instant allocation', 'Performance-based routing', 'Capacity balancing', 'Deviation alerts'],
  data_required = ARRAY['Installer performance scores', 'Capacity data', 'Region coverage'],
  data_generates = ARRAY['Allocation decisions', 'Quota tracking', 'Deviation alerts'],
  data_improves = ARRAY['Conversion rates', 'Installer satisfaction', 'Customer experience'],
  ops_process = 'Lead Allocation',
  current_loa = 'Manual',
  potential_loa = 'High Automation',
  resources_used = ARRAY['Deals', 'Opportunities', 'Regions', 'Installers'],
  api_endpoints = ARRAY['/internal/deals', '/internal/opportunities', '/internal/regions', '/internal/installers'],
  prerequisites = ARRAY['Performance tracking operational', 'Allocation rules defined'],
  benefits = ARRAY['Instant allocation', 'Optimal matching', 'Automatic quota balancing', 'Performance-based routing'],
  missing_api_data = ARRAY['Installer capacity', 'Weight targets', 'Deviation calculations'],
  integrations_needed = ARRAY['Installer Portal', 'SDR Portal'],
  depends_on = ARRAY['unified-data-layer', 'installer-performance-tracking'],
  enables = ARRAY[]::text[],
  related_to = ARRAY['funnel-automation-os'],
  primary_users = ARRAY['Operations'],
  data_status = 'Partial',
  next_milestone = 'Define allocation rules + scoring model',
  problem_statement = 'Ops manually assigns leads using Google Sheets. This is time-consuming, inconsistent, and leads to suboptimal matching between leads and installers.',
  deliverables = ARRAY['AI-powered allocation engine', 'Performance-based routing rules', 'Capacity balancing system', 'Deviation alerting']
WHERE slug = 'dynamic-allocation-engine';

-- 13. WhatsApp Conversation AI Summary
UPDATE projects SET
  human_role_before = 'SDRs spend 5-10 minutes reading WhatsApp history before each call.',
  human_role_after = 'SDRs get instant AI summary with key points. Jump straight into meaningful conversations.',
  who_is_empowered = ARRAY['SDRs'],
  new_capabilities = ARRAY['Instant context', 'Key points extraction', 'Suggested talking points'],
  data_required = ARRAY['Full WhatsApp conversation history', 'Message timestamps'],
  data_generates = ARRAY['Conversation summaries', 'Suggested responses'],
  data_improves = ARRAY['SDR efficiency', 'Call preparation time'],
  ops_process = 'Call Preparation',
  current_loa = 'Manual',
  potential_loa = 'High Automation',
  resources_used = ARRAY['Deals', 'Templates'],
  api_endpoints = ARRAY['/internal/deals', '/internal/deals/{id}/messages'],
  prerequisites = ARRAY['LLM integration', 'WhatsApp message history access'],
  benefits = ARRAY['Faster call prep', 'No context loss', 'Consistent information', 'Better customer experience'],
  missing_api_data = ARRAY['Full WhatsApp conversation history endpoint', 'Message direction field'],
  integrations_needed = ARRAY['OpenAI/Claude API'],
  depends_on = ARRAY['sdr-portal', 'unified-data-layer'],
  enables = ARRAY['ai-cortex'],
  related_to = ARRAY['funnel-automation-os'],
  primary_users = ARRAY['SDRs'],
  data_status = 'Partial',
  next_milestone = 'Build conversation history endpoint + LLM integration',
  problem_statement = 'SDRs spend 5-10 minutes reading through long WhatsApp message threads before each call. This wastes valuable time and leads to missed context.',
  deliverables = ARRAY['AI conversation summary engine', 'Key points extraction', 'Suggested talking points', 'SDR Portal integration']
WHERE slug = 'whatsapp-conversation-summary';

-- 14. AI Contact Prioritization
UPDATE projects SET
  human_role_before = 'SDRs guess who to call next based on gut feeling.',
  human_role_after = 'AI suggests optimal contact order. SDRs focus on execution, not decision-making.',
  who_is_empowered = ARRAY['SDRs', 'Team Leads'],
  new_capabilities = ARRAY['AI-ranked contact list', 'Optimal timing suggestions', 'Channel recommendations'],
  data_required = ARRAY['Historical contact patterns', 'Answer rates by time', 'Customer timezones'],
  data_generates = ARRAY['Priority scores', 'Contact recommendations', 'Timing suggestions'],
  data_improves = ARRAY['Answer rates', 'SDR efficiency', 'Conversion rates'],
  ops_process = 'Contact Prioritization',
  current_loa = 'Manual',
  potential_loa = 'High Automation',
  resources_used = ARRAY['Deals', 'Calls', 'Qualifications'],
  api_endpoints = ARRAY['/internal/deals', '/internal/calls', '/internal/qualifications'],
  prerequisites = ARRAY['ML model for scoring', 'Historical data analysis'],
  benefits = ARRAY['Higher answer rates', 'SDR focus on high-value contacts', 'Data-driven optimization'],
  missing_api_data = ARRAY['Historical contact attempt times', 'Answer rate by time-of-day', 'Customer preferred hours'],
  integrations_needed = ARRAY['ML pipeline'],
  depends_on = ARRAY['sdr-portal', 'unified-data-layer'],
  enables = ARRAY['ai-cortex'],
  related_to = ARRAY['funnel-automation-os'],
  primary_users = ARRAY['SDRs'],
  data_status = 'Partial',
  next_milestone = 'Build scoring model + SDR Portal integration',
  problem_statement = 'SDRs guess who to call next based on gut feeling. This leads to suboptimal contact sequencing and missed opportunities.',
  deliverables = ARRAY['AI contact scoring model', 'Optimal timing engine', 'Channel preference predictions', 'SDR Portal integration']
WHERE slug = 'contact-prioritization-engine';

-- 15. Lead Recycling Workflow
UPDATE projects SET
  human_role_before = 'Lost leads disappear into a black hole. No systematic re-engagement.',
  human_role_after = 'System automatically identifies recyclable leads. Ops reviews and approves re-engagement.',
  who_is_empowered = ARRAY['Operations', 'SDRs'],
  new_capabilities = ARRAY['Automatic recyclable identification', 'Optimal re-engagement timing', 'Outcome tracking'],
  data_required = ARRAY['Lost reason with recyclable flag', 'Recycling attempt count'],
  data_generates = ARRAY['Recycling queue', 'Re-engagement schedule', 'Outcome data'],
  data_improves = ARRAY['Total conversion rate', 'Lead utilization'],
  ops_process = 'Recycling Workflow',
  current_loa = 'Manual',
  potential_loa = 'High Automation',
  resources_used = ARRAY['Deals', 'Opportunities', 'Lost Reasons'],
  api_endpoints = ARRAY['/internal/deals', '/internal/opportunities', '/internal/lost-reasons'],
  prerequisites = ARRAY['Installer CRM integrations', 'Recycling rules'],
  benefits = ARRAY['Recover lost revenue', 'Automatic re-assignment', 'Track recycling success'],
  missing_api_data = ARRAY['Recyclable flag on lost reasons', 'Recycling attempt count per deal', 'Re-engagement cooldown rules'],
  integrations_needed = ARRAY['Installer CRM webhooks'],
  depends_on = ARRAY['unified-data-layer'],
  enables = ARRAY[]::text[],
  related_to = ARRAY['funnel-automation-os'],
  primary_users = ARRAY['Operations'],
  data_status = 'Partial',
  next_milestone = 'Add recyclable flags + build workflow',
  problem_statement = 'Lost leads disappear into a black hole with no systematic way to re-engage them. Potential revenue is left on the table.',
  deliverables = ARRAY['Recyclable lead identification system', 'Re-engagement timing optimizer', 'Recycling workflow automation', 'Outcome tracking dashboard']
WHERE slug = 'lead-recycling-workflow';

-- 16. Installer Feedback Collection
UPDATE projects SET
  human_role_before = 'Installer feedback is informal and lost. No systematic learning.',
  human_role_after = 'Structured feedback collection. Data used to coach SDRs and improve AI.',
  who_is_empowered = ARRAY['Installers', 'SDR Team Leads', 'Operations'],
  new_capabilities = ARRAY['Structured feedback', 'Pattern identification', 'Continuous improvement'],
  data_required = ARRAY['Feedback categories', 'Installer ID per feedback'],
  data_generates = ARRAY['Feedback patterns', 'SDR coaching insights', 'AI improvement data'],
  data_improves = ARRAY['Lead quality', 'SDR performance', 'AI accuracy'],
  ops_process = 'Feedback Collection',
  current_loa = 'Not Implemented',
  potential_loa = 'High Automation',
  resources_used = ARRAY['Opportunities', 'Installers', 'Lost Reasons'],
  api_endpoints = ARRAY['/internal/opportunities', '/internal/installers', '/internal/lost-reasons'],
  prerequisites = ARRAY['Feedback form/API', 'Dashboard with filtering'],
  benefits = ARRAY['Systematic feedback', 'Pattern identification', 'Continuous improvement'],
  missing_api_data = ARRAY['Installer feedback endpoint', 'Feedback categories', 'Feedback timestamps'],
  integrations_needed = ARRAY['Installer Portal'],
  depends_on = ARRAY['installer-portal-product'],
  enables = ARRAY['ai-cortex'],
  related_to = ARRAY['installer-performance-tracking'],
  primary_users = ARRAY['Installers', 'Team Leads'],
  data_status = 'None',
  next_milestone = 'Design feedback form + API endpoint',
  problem_statement = 'Installer feedback is informal, inconsistent, and gets lost. There is no systematic way to learn from installer experiences and improve lead quality.',
  deliverables = ARRAY['Structured feedback collection system', 'Pattern analysis dashboard', 'SDR coaching insights', 'AI training data pipeline']
WHERE slug = 'installer-feedback-system';

-- 17. Installer Quote Sync
UPDATE projects SET
  human_role_before = 'Quote amounts unknown. Manual tracking in spreadsheets.',
  human_role_after = 'Installers submit quotes through portal. Automatic sync to CRM.',
  who_is_empowered = ARRAY['Operations', 'Finance', 'Installers'],
  new_capabilities = ARRAY['Price benchmarking', 'Revenue tracking', 'Financing integration'],
  data_required = ARRAY['Offer amount field on opportunities', 'Installer webhook endpoint'],
  data_generates = ARRAY['Quote data', 'Price benchmarks', 'Revenue forecasts'],
  data_improves = ARRAY['ROI accuracy', 'Financial planning'],
  ops_process = 'Quote Collection',
  current_loa = 'Not Implemented',
  potential_loa = 'Medium Automation',
  resources_used = ARRAY['Opportunities', 'Installers'],
  api_endpoints = ARRAY['/internal/opportunities', '/internal/installers'],
  prerequisites = ARRAY['Webhook endpoint for installers', 'Data validation'],
  benefits = ARRAY['Enable financing partnerships', 'Accurate revenue tracking', 'Price benchmarking'],
  missing_api_data = ARRAY['Offer amount field', 'Offer timestamp', 'Installer webhook POST endpoint'],
  integrations_needed = ARRAY['Installer Portal'],
  depends_on = ARRAY['installer-portal-product'],
  enables = ARRAY[]::text[],
  related_to = ARRAY['reporting-hub'],
  primary_users = ARRAY['Installers', 'Operations'],
  data_status = 'None',
  next_milestone = 'Add offer amount field + webhook endpoint',
  problem_statement = 'Quote amounts from installers are unknown and tracked manually in spreadsheets. This prevents accurate ROI tracking and financing partnerships.',
  deliverables = ARRAY['Quote submission interface', 'CRM sync automation', 'Price benchmarking tools', 'Revenue forecasting integration']
WHERE slug = 'installer-quote-sync';

-- 18. Answer Rate Monitor
UPDATE projects SET
  human_role_before = 'Number issues discovered when answer rates drop. Reactive.',
  human_role_after = 'Automated monitoring alerts before problems impact performance.',
  who_is_empowered = ARRAY['Operations', 'SDR Team Leads'],
  new_capabilities = ARRAY['Proactive SIM rotation', 'Answer rate tracking', 'Spam detection'],
  data_required = ARRAY['Outbound number per call', 'Answer rate aggregation'],
  data_generates = ARRAY['Number health scores', 'Rotation alerts'],
  data_improves = ARRAY['Answer rates', 'Call efficiency'],
  ops_process = 'Answer Rate Monitoring',
  current_loa = 'Manual',
  potential_loa = 'Medium Automation',
  resources_used = ARRAY['Calls', 'Unmatched Calls'],
  api_endpoints = ARRAY['/internal/calls', '/internal/calls/stats', '/internal/unmatched-calls'],
  prerequisites = ARRAY['Aircall integration', 'Alerting system'],
  benefits = ARRAY['Maintain high answer rates', 'Proactive SIM rotation', 'Reduce wasted attempts'],
  missing_api_data = ARRAY['Outbound number identifier per call', 'Spam flag detection', 'Answer rate by number'],
  integrations_needed = ARRAY['Aircall'],
  depends_on = ARRAY['unified-data-layer'],
  enables = ARRAY[]::text[],
  related_to = ARRAY['reporting-hub'],
  primary_users = ARRAY['Operations'],
  data_status = 'Partial',
  next_milestone = 'Add outbound number tracking + alerting',
  problem_statement = 'Phone number issues are only discovered when answer rates drop significantly. There is no proactive monitoring for spam flags or degrading performance.',
  deliverables = ARRAY['Number health monitoring dashboard', 'Spam detection alerting', 'Proactive rotation recommendations', 'Historical performance tracking']
WHERE slug = 'answer-rate-monitoring';

-- 19. GDPR Compliance Tracker
UPDATE projects SET
  human_role_before = 'Consent tracked informally. Legal exposure unknown.',
  human_role_after = 'Automated consent tracking. Clear audit trail. Legal peace of mind.',
  who_is_empowered = ARRAY['Legal', 'Operations', 'Leadership'],
  new_capabilities = ARRAY['Consent audit trail', 'Auto-anonymization', 'Compliance reporting'],
  data_required = ARRAY['Consent flag per deal', 'Consent timestamp', 'Opt-out tracking'],
  data_generates = ARRAY['Compliance reports', 'Anonymization logs', 'Audit trail'],
  data_improves = ARRAY['Legal compliance', 'Customer trust'],
  ops_process = 'GDPR Compliance',
  current_loa = 'Not Implemented',
  potential_loa = 'High Automation',
  resources_used = ARRAY['Deals', 'Qualifications'],
  api_endpoints = ARRAY['/internal/deals', '/internal/qualifications'],
  prerequisites = ARRAY['Consent tracking system', 'Anonymization logic'],
  benefits = ARRAY['Legal compliance', 'Automated data retention', 'Audit-ready reports'],
  missing_api_data = ARRAY['Consent flag and source per deal', 'Consent timestamp', 'Opt-out tracking', 'Data retention config'],
  integrations_needed = ARRAY['Data retention system'],
  depends_on = ARRAY['unified-data-layer'],
  enables = ARRAY[]::text[],
  related_to = ARRAY['data-quality-monitor'],
  primary_users = ARRAY['Legal', 'Operations'],
  data_status = 'None',
  next_milestone = 'Define consent fields + retention policy',
  problem_statement = 'GDPR consent is tracked informally with unknown legal exposure. Violations can result in €40k-€300k fines.',
  deliverables = ARRAY['Consent tracking system', 'Auto-anonymization engine', 'Compliance reporting dashboard', 'Audit trail documentation']
WHERE slug = 'gdpr-compliance-tracker';

-- 20. Automated Invoicing
UPDATE projects SET
  human_role_before = 'Finance spends hours on monthly invoicing. Frequent disputes.',
  human_role_after = 'Automated invoice generation. Finance reviews and approves.',
  who_is_empowered = ARRAY['Finance', 'Operations'],
  new_capabilities = ARRAY['Automated invoice generation', 'Reconciliation', 'Dispute reduction'],
  data_required = ARRAY['Provider pricing/CPL data', 'Validation status', 'Won opportunity revenue'],
  data_generates = ARRAY['Invoices', 'Reconciliation reports'],
  data_improves = ARRAY['Finance efficiency', 'Partner relationships'],
  ops_process = 'Invoicing',
  current_loa = 'Manual',
  potential_loa = 'Medium Automation',
  resources_used = ARRAY['Deals', 'Opportunities', 'Installers'],
  api_endpoints = ARRAY['/internal/deals/stats', '/internal/opportunities/stats'],
  prerequisites = ARRAY['Accounting rules engine', 'PDF generation'],
  benefits = ARRAY['Hours saved on invoicing', 'Fewer disputes', 'Clear audit trail'],
  missing_api_data = ARRAY['Provider pricing/CPL data', 'Invoice line item breakdown'],
  integrations_needed = ARRAY['Accounting system'],
  depends_on = ARRAY['reporting-hub'],
  enables = ARRAY[]::text[],
  related_to = ARRAY['installer-quote-sync'],
  primary_users = ARRAY['Finance'],
  data_status = 'Partial',
  next_milestone = 'Define invoicing rules + template',
  problem_statement = 'Finance spends hours each month on manual invoicing. Frequent disputes with providers and installers waste time and damage relationships.',
  deliverables = ARRAY['Automated invoice generation', 'Reconciliation dashboard', 'Dispute tracking system', 'Integration with accounting']
WHERE slug = 'automated-invoicing';

-- 21. Provider API Self-Service Portal
UPDATE projects SET
  human_role_before = 'Tech team manually onboards each provider. High support burden.',
  human_role_after = 'Providers self-serve API integration. Tech reviews edge cases only.',
  who_is_empowered = ARRAY['Tech Team', 'Partner Ops', 'Providers'],
  new_capabilities = ARRAY['Self-service onboarding', 'Real-time testing', 'Error debugging'],
  data_required = ARRAY['Provider auth tokens', 'Webhook logs', 'Integration health'],
  data_generates = ARRAY['Integration status', 'Error logs', 'Usage metrics'],
  data_improves = ARRAY['Provider onboarding speed', 'Support efficiency'],
  ops_process = 'Provider Onboarding',
  current_loa = 'Manual',
  potential_loa = 'High Automation',
  resources_used = ARRAY['Deals'],
  api_endpoints = ARRAY['/internal/deals'],
  prerequisites = ARRAY['Auth system', 'Webhook monitoring', 'Documentation'],
  benefits = ARRAY['Faster provider onboarding', 'Reduced support', 'Better integration quality'],
  missing_api_data = ARRAY['Provider auth tokens', 'Webhook delivery logs', 'Integration health per provider'],
  integrations_needed = ARRAY['Auth0/custom auth'],
  depends_on = ARRAY['unified-data-layer'],
  enables = ARRAY[]::text[],
  related_to = ARRAY['campaign-os'],
  primary_users = ARRAY['Providers', 'Tech'],
  data_status = 'None',
  next_milestone = 'Build documentation portal + API sandbox',
  problem_statement = 'Tech team manually onboards each lead provider with high support burden. This slows down partnership growth and wastes engineering time.',
  deliverables = ARRAY['Self-service API portal', 'Real-time testing sandbox', 'Integration health dashboard', 'Automated documentation']
WHERE slug = 'api-self-service-portal';

-- 22. Programmatic SEO Pages
UPDATE projects SET
  human_role_before = 'Marketing creates pages manually. Only covering 50-100 cities.',
  human_role_after = 'AI generates thousands of pages. Marketing focuses on strategy and optimization.',
  who_is_empowered = ARRAY['Marketing', 'Growth', 'SEO'],
  new_capabilities = ARRAY['Massive organic reach', 'Long-tail dominance', 'Zero-cost traffic'],
  data_required = ARRAY['PVGIS solar data', 'INE municipality data', 'Municipal incentives'],
  data_generates = ARRAY['Organic traffic', 'Local leads', 'SEO authority'],
  data_improves = ARRAY['CAC', 'Brand awareness', 'Organic lead volume'],
  ops_process = 'SEO & Content',
  current_loa = 'Not Implemented',
  potential_loa = 'High Automation',
  resources_used = ARRAY['External APIs'],
  api_endpoints = ARRAY[]::text[],
  prerequisites = ARRAY['PVGIS API', 'ESIOS API', 'Municipal data scraper'],
  benefits = ARRAY['8000+ pages with zero competition', 'Massive organic traffic', '-60% CAC'],
  missing_api_data = ARRAY['PVGIS integration', 'Municipal incentives database'],
  integrations_needed = ARRAY['PVGIS', 'ESIOS', 'INE data'],
  depends_on = ARRAY[]::text[],
  enables = ARRAY['campaign-os'],
  related_to = ARRAY['pvpc-savings-widget', 'irpf-calculator'],
  primary_users = ARRAY['Marketing'],
  data_status = 'None',
  next_milestone = 'Build 500 pilot pages for top municipalities',
  problem_statement = 'Marketing creates SEO pages manually, covering only 50-100 cities. Spain has 8,131 municipalities with 90%+ having zero solar installer SEO pages.',
  deliverables = ARRAY['8000+ programmatic SEO pages', 'Municipality data integration', 'Solar yield calculator per location', 'Automated page generation system']
WHERE slug = 'programmatic-seo-pages';

-- 23. PVPC Savings Widget
UPDATE projects SET
  human_role_before = 'Static savings estimates. No real-time engagement.',
  human_role_after = 'Real-time pricing creates urgency. Widget drives viral sharing.',
  who_is_empowered = ARRAY['Marketing', 'Growth'],
  new_capabilities = ARRAY['Real-time engagement', 'Viral sharing', 'Daily habit formation'],
  data_required = ARRAY['ESIOS real-time PVPC data'],
  data_generates = ARRAY['Engagement', 'Social shares', 'Leads'],
  data_improves = ARRAY['Website engagement', 'Viral reach'],
  ops_process = 'Lead Generation',
  current_loa = 'Not Implemented',
  potential_loa = 'Fully Automated',
  resources_used = ARRAY['External APIs'],
  api_endpoints = ARRAY[]::text[],
  prerequisites = ARRAY['ESIOS API integration'],
  benefits = ARRAY['High engagement', 'Viral potential', '-40% CAC via organic'],
  missing_api_data = ARRAY['ESIOS API integration'],
  integrations_needed = ARRAY['ESIOS/REE API'],
  depends_on = ARRAY[]::text[],
  enables = ARRAY['programmatic-seo-pages'],
  related_to = ARRAY['irpf-calculator'],
  primary_users = ARRAY['Marketing'],
  data_status = 'None',
  next_milestone = 'Build standalone microsite first',
  problem_statement = 'Static savings estimates provide no real-time engagement. Spaniards check electricity prices obsessively but we are not capitalizing on this behavior.',
  deliverables = ARRAY['Real-time PVPC price widget', 'Personalized savings calculator', 'Social sharing integration', 'Viral loop mechanism']
WHERE slug = 'pvpc-savings-widget';

-- 24. IRPF Calculator
UPDATE projects SET
  human_role_before = 'Tax benefits explained in text. No personalization.',
  human_role_after = 'Interactive calculator shows exact savings. Urgency drives conversions.',
  who_is_empowered = ARRAY['Marketing', 'Sales'],
  new_capabilities = ARRAY['Personalized tax calculations', 'Urgency messaging', 'Conversion optimization'],
  data_required = ARRAY['IRPF rules', 'Tax bracket data'],
  data_generates = ARRAY['Calculator usage data', 'Lead conversion'],
  data_improves = ARRAY['Conversion rate', 'Urgency perception'],
  ops_process = 'Lead Generation',
  current_loa = 'Not Implemented',
  potential_loa = 'Fully Automated',
  resources_used = ARRAY[]::text[],
  api_endpoints = ARRAY[]::text[],
  prerequisites = ARRAY['IRPF deduction rules'],
  benefits = ARRAY['Urgency trigger', 'Higher conversions', '-30% CAC'],
  missing_api_data = ARRAY[]::text[],
  integrations_needed = ARRAY[]::text[],
  depends_on = ARRAY[]::text[],
  enables = ARRAY['programmatic-seo-pages'],
  related_to = ARRAY['pvpc-savings-widget'],
  primary_users = ARRAY['Marketing'],
  data_status = 'None',
  next_milestone = 'Build calculator + embed on all pages',
  problem_statement = 'Most Spaniards do not know about the 60% IRPF tax deduction for solar. Tax benefits are explained in text with no personalization.',
  deliverables = ARRAY['Interactive IRPF calculator', 'Tax bracket integration', 'Urgency countdown feature', 'Embedded widget for all pages']
WHERE slug = 'irpf-calculator';

-- 25. GMB Automation
UPDATE projects SET
  human_role_before = 'Single GMB profile. Limited local visibility.',
  human_role_after = 'Automated multi-location presence. AI handles posts and review responses.',
  who_is_empowered = ARRAY['Marketing', 'Operations'],
  new_capabilities = ARRAY['Local pack dominance', 'Automated posts', 'AI review responses'],
  data_required = ARRAY['GMB API access', 'Service area data'],
  data_generates = ARRAY['Local visibility', 'Reviews', 'Local leads'],
  data_improves = ARRAY['Local SEO', 'Trust signals'],
  ops_process = 'Local Marketing',
  current_loa = 'Manual',
  potential_loa = 'High Automation',
  resources_used = ARRAY['Opportunities', 'Installers'],
  api_endpoints = ARRAY[]::text[],
  prerequisites = ARRAY['GMB API', 'Automation framework'],
  benefits = ARRAY['Local pack visibility', 'Zero-cost clicks', '-45% CAC'],
  missing_api_data = ARRAY[]::text[],
  integrations_needed = ARRAY['Google Business API'],
  depends_on = ARRAY[]::text[],
  enables = ARRAY['review-generation-system'],
  related_to = ARRAY['programmatic-seo-pages'],
  primary_users = ARRAY['Marketing'],
  data_status = 'None',
  next_milestone = 'Set up 10 pilot profiles',
  problem_statement = 'We have a single Google Business profile with limited local visibility. Local pack results drive highest intent clicks at zero cost.',
  deliverables = ARRAY['50+ automated GMB profiles', 'AI-powered post generation', 'Automated review responses', 'Local visibility dashboard']
WHERE slug = 'gmb-automation';

-- 26. Review Generation System
UPDATE projects SET
  human_role_before = 'Reviews happen randomly. No systematic collection.',
  human_role_after = 'Automated request sequence. AI responds within 2 hours.',
  who_is_empowered = ARRAY['Marketing', 'Operations'],
  new_capabilities = ARRAY['Systematic review collection', 'Fast response times', 'Social proof at scale'],
  data_required = ARRAY['Installation completion dates', 'Customer contact info'],
  data_generates = ARRAY['Reviews', 'Social proof', 'Testimonials'],
  data_improves = ARRAY['Trust', 'Conversion rate'],
  ops_process = 'Review Management',
  current_loa = 'Not Implemented',
  potential_loa = 'High Automation',
  resources_used = ARRAY['Opportunities', 'Installers'],
  api_endpoints = ARRAY['/internal/opportunities'],
  prerequisites = ARRAY['WhatsApp automation', 'GMB API'],
  benefits = ARRAY['Systematic social proof', '-25% CAC via trust', 'Referral loop'],
  missing_api_data = ARRAY['Installation completion date field'],
  integrations_needed = ARRAY['GMB API', 'WhatsApp'],
  depends_on = ARRAY['unified-data-layer'],
  enables = ARRAY[]::text[],
  related_to = ARRAY['gmb-automation'],
  primary_users = ARRAY['Marketing'],
  data_status = 'Partial',
  next_milestone = 'Build review request flow',
  problem_statement = 'Reviews happen randomly with no systematic collection. Spanish trust factor means Reviews > Ads.',
  deliverables = ARRAY['Automated review request sequences', 'AI review response system', 'Social proof tracking dashboard', 'Referral program integration']
WHERE slug = 'review-generation-system';

-- 27. Competitor Intel Agent
UPDATE projects SET
  human_role_before = 'Marketing manually checks competitor ads occasionally.',
  human_role_after = 'Daily automated intel. AI suggests counter-strategies.',
  who_is_empowered = ARRAY['Marketing', 'Growth'],
  new_capabilities = ARRAY['Real-time competitor tracking', 'Gap identification', 'AI strategy suggestions'],
  data_required = ARRAY['Meta Ad Library access', 'Google Ads Transparency'],
  data_generates = ARRAY['Competitor insights', 'Creative gaps', 'Strategy recommendations'],
  data_improves = ARRAY['Ad efficiency', 'Creative quality'],
  ops_process = 'Competitive Intelligence',
  current_loa = 'Manual',
  potential_loa = 'High Automation',
  resources_used = ARRAY['External APIs'],
  api_endpoints = ARRAY[]::text[],
  prerequisites = ARRAY['Ad library scrapers', 'AI analysis pipeline'],
  benefits = ARRAY['Avoid wasted spend', 'Find untapped angles', '-20% CAC'],
  missing_api_data = ARRAY[]::text[],
  integrations_needed = ARRAY['Meta Ad Library', 'Claude API'],
  depends_on = ARRAY[]::text[],
  enables = ARRAY['campaign-os'],
  related_to = ARRAY[]::text[],
  primary_users = ARRAY['Marketing'],
  data_status = 'None',
  next_milestone = 'Build scraper + weekly reports',
  problem_statement = 'Marketing manually checks competitor ads occasionally with no systematic tracking. This leads to wasted ad spend on losing angles.',
  deliverables = ARRAY['Daily competitor ad scraping', 'AI-powered gap analysis', 'Counter-strategy recommendations', 'Weekly competitive reports']
WHERE slug = 'competitor-intel-agent';

-- 28. Robinson Suppressor
UPDATE projects SET
  human_role_before = 'Manual Robinson checks. Risk of violations.',
  human_role_after = 'Automated nightly suppression. Zero compliance risk.',
  who_is_empowered = ARRAY['Legal', 'Operations'],
  new_capabilities = ARRAY['Automated suppression', 'CLI registration', 'Compliance audit trail'],
  data_required = ARRAY['Robinson list access', 'Phone hashing'],
  data_generates = ARRAY['Suppression logs', 'Compliance reports'],
  data_improves = ARRAY['Legal compliance', 'Call efficiency'],
  ops_process = 'Compliance',
  current_loa = 'Not Implemented',
  potential_loa = 'Fully Automated',
  resources_used = ARRAY['Deals'],
  api_endpoints = ARRAY['/internal/deals'],
  prerequisites = ARRAY['Robinson list API', 'Nightly job scheduler'],
  benefits = ARRAY['Avoid €40k-€300k fines', 'Protect call capability', 'Legal peace of mind'],
  missing_api_data = ARRAY['Robinson list integration'],
  integrations_needed = ARRAY['Robinson list API'],
  depends_on = ARRAY['unified-data-layer'],
  enables = ARRAY[]::text[],
  related_to = ARRAY['gdpr-compliance-tracker'],
  primary_users = ARRAY['Legal', 'Operations'],
  data_status = 'None',
  next_milestone = 'Build suppression agent + CLI registration',
  problem_statement = 'Robinson list checks are done manually with risk of violations. Violations result in €40k-€300k fines and potential call blocking.',
  deliverables = ARRAY['Automated nightly suppression', 'CLI registration system', 'Compliance audit trail', 'Alert system for new additions']
WHERE slug = 'robinson-suppressor';

-- 29. Unified Quote API
UPDATE projects SET
  human_role_before = 'Different prices on website, ads, WhatsApp. Customer confusion.',
  human_role_after = 'Consistent pricing everywhere. Sales focuses on closing, not explaining discrepancies.',
  who_is_empowered = ARRAY['Sales', 'Marketing', 'Operations'],
  new_capabilities = ARRAY['Consistent pricing', 'Real-time quotes', 'Dynamic calculations'],
  data_required = ARRAY['PVGIS yield data', 'PVPC rates', 'Municipal incentives', 'Equipment pricing'],
  data_generates = ARRAY['Instant quotes', 'Savings calculations', 'Payback estimates'],
  data_improves = ARRAY['Trust', 'Conversion rate', 'Sales efficiency'],
  ops_process = 'Quoting',
  current_loa = 'Manual',
  potential_loa = 'Fully Automated',
  resources_used = ARRAY['Deals', 'Regions'],
  api_endpoints = ARRAY['/internal/deals', '/internal/regions'],
  prerequisites = ARRAY['PVGIS API', 'ESIOS API', 'Pricing database'],
  benefits = ARRAY['Consistent pricing', 'Higher trust', '-35% CAC via consistency'],
  missing_api_data = ARRAY['PVGIS integration', 'Municipal incentives', 'Equipment pricing'],
  integrations_needed = ARRAY['PVGIS', 'ESIOS'],
  depends_on = ARRAY['unified-data-layer'],
  enables = ARRAY['funnel-automation-os', 'programmatic-seo-pages'],
  related_to = ARRAY['irpf-calculator', 'pvpc-savings-widget'],
  primary_users = ARRAY['All teams'],
  data_status = 'None',
  next_milestone = 'Build basic quote API + integrate with website',
  problem_statement = 'Different prices appear on website, ads, and WhatsApp causing customer confusion. Inconsistent pricing damages trust and loses deals.',
  deliverables = ARRAY['Unified quote calculation API', 'Real-time pricing engine', 'Municipal incentives database', 'Integration with all touchpoints']
WHERE slug = 'unified-quote-api';

-- Verify the update worked
SELECT slug, title,
  CASE WHEN problem_statement IS NOT NULL THEN 'Has problem' ELSE 'Missing' END as problem_status,
  CASE WHEN array_length(deliverables, 1) > 0 THEN 'Has deliverables' ELSE 'Missing' END as deliverables_status,
  CASE WHEN human_role_before IS NOT NULL THEN 'Has human role' ELSE 'Missing' END as human_role_status
FROM projects
ORDER BY title;
